# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Full DesignYyFuCN.ui'
##
## Created by: Qt User Interface Compiler version 6.8.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QDial,
    QFrame, QGroupBox, QHeaderView, QLCDNumber,
    QLabel, QLineEdit, QMainWindow, QMenu,
    QMenuBar, QProgressBar, QPushButton, QSizePolicy,
    QSlider, QStatusBar, QTabWidget, QTableWidget,
    QTableWidgetItem, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1198, 696)
        font = QFont()
        font.setPointSize(11)
        MainWindow.setFont(font)
        self.fileNew = QAction(MainWindow)
        self.fileNew.setObjectName(u"fileNew")
        self.fileOpen = QAction(MainWindow)
        self.fileOpen.setObjectName(u"fileOpen")
        self.fileSave = QAction(MainWindow)
        self.fileSave.setObjectName(u"fileSave")
        self.fileExport = QAction(MainWindow)
        self.fileExport.setObjectName(u"fileExport")
        self.fileExit = QAction(MainWindow)
        self.fileExit.setObjectName(u"fileExit")
        self.actionviewCreateDataset = QAction(MainWindow)
        self.actionviewCreateDataset.setObjectName(u"actionviewCreateDataset")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.MainTab = QTabWidget(self.centralwidget)
        self.MainTab.setObjectName(u"MainTab")
        self.MainTab.setEnabled(True)
        self.MainTab.setGeometry(QRect(0, 30, 1200, 601))
        font1 = QFont()
        font1.setFamilies([u"Segoe UI"])
        font1.setPointSize(18)
        self.MainTab.setFont(font1)
        self.MainTab.setStyleSheet(u"border-color: rgb(0, 0, 0);")
        self.MainTab.setTabPosition(QTabWidget.TabPosition.North)
        self.MainTab.setTabShape(QTabWidget.TabShape.Rounded)
        self.MainTab.setIconSize(QSize(16, 16))
        self.MainTab.setElideMode(Qt.TextElideMode.ElideNone)
        self.importVideo = QWidget()
        self.importVideo.setObjectName(u"importVideo")
        self.video_preview_label = QLabel(self.importVideo)
        self.video_preview_label.setObjectName(u"video_preview_label")
        self.video_preview_label.setGeometry(QRect(10, 10, 471, 281))
        font2 = QFont()
        font2.setPointSize(16)
        font2.setItalic(True)
        self.video_preview_label.setFont(font2)
        self.video_preview_label.setFrameShape(QFrame.Shape.WinPanel)
        self.video_preview_label.setFrameShadow(QFrame.Shadow.Raised)
        self.video_preview_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.groupBox_2 = QGroupBox(self.importVideo)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(970, 0, 221, 551))
        font3 = QFont()
        font3.setPointSize(12)
        self.groupBox_2.setFont(font3)
        self.frame_6 = QFrame(self.groupBox_2)
        self.frame_6.setObjectName(u"frame_6")
        self.frame_6.setGeometry(QRect(10, 290, 201, 251))
        self.frame_6.setFrameShape(QFrame.Shape.Box)
        self.frame_6.setFrameShadow(QFrame.Shadow.Sunken)
        self.label_34 = QLabel(self.frame_6)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(10, 10, 121, 31))
        font4 = QFont()
        font4.setPointSize(9)
        self.label_34.setFont(font4)
        self.human_detect_conf_slider = QSlider(self.frame_6)
        self.human_detect_conf_slider.setObjectName(u"human_detect_conf_slider")
        self.human_detect_conf_slider.setGeometry(QRect(20, 50, 160, 22))
        self.human_detect_conf_slider.setMaximum(100)
        self.human_detect_conf_slider.setSingleStep(5)
        self.human_detect_conf_slider.setPageStep(5)
        self.human_detect_conf_slider.setValue(60)
        self.human_detect_conf_slider.setOrientation(Qt.Orientation.Horizontal)
        self.confLineEdit = QLineEdit(self.frame_6)
        self.confLineEdit.setObjectName(u"confLineEdit")
        self.confLineEdit.setGeometry(QRect(120, 10, 51, 31))
        font5 = QFont()
        font5.setPointSize(14)
        font5.setBold(True)
        self.confLineEdit.setFont(font5)
        self.confLineEdit.setReadOnly(True)
        self.label_35 = QLabel(self.frame_6)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(170, 10, 31, 31))
        font6 = QFont()
        font6.setPointSize(14)
        self.label_35.setFont(font6)
        self.label_35.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_36 = QLabel(self.frame_6)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(10, 140, 111, 21))
        font7 = QFont()
        font7.setPointSize(10)
        self.label_36.setFont(font7)
        self.label_37 = QLabel(self.frame_6)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(170, 140, 31, 31))
        self.label_37.setFont(font6)
        self.label_37.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.fpsLoadingRateLineEdit = QLineEdit(self.frame_6)
        self.fpsLoadingRateLineEdit.setObjectName(u"fpsLoadingRateLineEdit")
        self.fpsLoadingRateLineEdit.setGeometry(QRect(120, 140, 51, 31))
        self.fpsLoadingRateLineEdit.setFont(font5)
        self.fpsLoadingRateLineEdit.setReadOnly(True)
        self.fps_loading_rate_slider = QSlider(self.frame_6)
        self.fps_loading_rate_slider.setObjectName(u"fps_loading_rate_slider")
        self.fps_loading_rate_slider.setGeometry(QRect(20, 180, 160, 22))
        self.fps_loading_rate_slider.setMinimum(1)
        self.fps_loading_rate_slider.setMaximum(60)
        self.fps_loading_rate_slider.setSingleStep(1)
        self.fps_loading_rate_slider.setPageStep(1)
        self.fps_loading_rate_slider.setValue(30)
        self.fps_loading_rate_slider.setOrientation(Qt.Orientation.Horizontal)
        self.fps_loading_rate_slider.setTickPosition(QSlider.TickPosition.TicksAbove)
        self.fps_loading_rate_slider.setTickInterval(10)
        self.label_38 = QLabel(self.frame_6)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(10, 70, 121, 31))
        self.label_38.setFont(font4)
        self.human_pose_conf_slider = QSlider(self.frame_6)
        self.human_pose_conf_slider.setObjectName(u"human_pose_conf_slider")
        self.human_pose_conf_slider.setGeometry(QRect(20, 110, 160, 22))
        self.human_pose_conf_slider.setMaximum(100)
        self.human_pose_conf_slider.setSingleStep(5)
        self.human_pose_conf_slider.setPageStep(5)
        self.human_pose_conf_slider.setValue(60)
        self.human_pose_conf_slider.setOrientation(Qt.Orientation.Horizontal)
        self.label_39 = QLabel(self.frame_6)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(170, 80, 31, 31))
        self.label_39.setFont(font6)
        self.label_39.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.confLineEdit_2 = QLineEdit(self.frame_6)
        self.confLineEdit_2.setObjectName(u"confLineEdit_2")
        self.confLineEdit_2.setGeometry(QRect(120, 80, 51, 31))
        self.confLineEdit_2.setFont(font5)
        self.confLineEdit_2.setReadOnly(True)
        self.show_2 = QPushButton(self.frame_6)
        self.show_2.setObjectName(u"show_2")
        self.show_2.setEnabled(True)
        self.show_2.setGeometry(QRect(20, 210, 161, 31))
        self.show_2.setFont(font3)
        self.frame_7 = QFrame(self.groupBox_2)
        self.frame_7.setObjectName(u"frame_7")
        self.frame_7.setGeometry(QRect(10, 30, 201, 251))
        self.frame_7.setFrameShape(QFrame.Shape.Box)
        self.frame_7.setFrameShadow(QFrame.Shadow.Sunken)
        self.frame_7.setLineWidth(1)
        self.label_23 = QLabel(self.frame_7)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(10, 60, 91, 21))
        font8 = QFont()
        font8.setPointSize(10)
        font8.setItalic(False)
        self.label_23.setFont(font8)
        self.label_23.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.top_left_x_dial = QDial(self.frame_7)
        self.top_left_x_dial.setObjectName(u"top_left_x_dial")
        self.top_left_x_dial.setGeometry(QRect(10, 80, 50, 51))
        self.top_left_x_dial.setInvertedAppearance(False)
        self.top_left_x_dial.setInvertedControls(False)
        self.top_left_y_dial = QDial(self.frame_7)
        self.top_left_y_dial.setObjectName(u"top_left_y_dial")
        self.top_left_y_dial.setGeometry(QRect(50, 80, 50, 51))
        self.top_right_x_dial = QDial(self.frame_7)
        self.top_right_x_dial.setObjectName(u"top_right_x_dial")
        self.top_right_x_dial.setGeometry(QRect(100, 80, 50, 51))
        self.top_right_y_dial = QDial(self.frame_7)
        self.top_right_y_dial.setObjectName(u"top_right_y_dial")
        self.top_right_y_dial.setGeometry(QRect(140, 80, 50, 51))
        self.label_24 = QLabel(self.frame_7)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(100, 60, 91, 21))
        self.label_24.setFont(font8)
        self.label_24.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_27 = QLabel(self.frame_7)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(0, 0, 201, 61))
        font9 = QFont()
        font9.setPointSize(14)
        font9.setItalic(True)
        self.label_27.setFont(font9)
        self.label_27.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_25 = QLabel(self.frame_7)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(100, 160, 101, 21))
        self.label_25.setFont(font8)
        self.label_25.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_26 = QLabel(self.frame_7)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(10, 160, 91, 21))
        self.label_26.setFont(font8)
        self.label_26.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.bottom_right_y_dial = QDial(self.frame_7)
        self.bottom_right_y_dial.setObjectName(u"bottom_right_y_dial")
        self.bottom_right_y_dial.setGeometry(QRect(140, 180, 50, 51))
        self.bottom_right_x_dial = QDial(self.frame_7)
        self.bottom_right_x_dial.setObjectName(u"bottom_right_x_dial")
        self.bottom_right_x_dial.setGeometry(QRect(100, 180, 50, 51))
        self.label_28 = QLabel(self.frame_7)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(0, 120, 111, 21))
        font10 = QFont()
        font10.setPointSize(12)
        font10.setItalic(False)
        self.label_28.setFont(font10)
        self.label_28.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_31 = QLabel(self.frame_7)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(90, 120, 111, 21))
        self.label_31.setFont(font10)
        self.label_31.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.bottom_left_y_dial = QDial(self.frame_7)
        self.bottom_left_y_dial.setObjectName(u"bottom_left_y_dial")
        self.bottom_left_y_dial.setGeometry(QRect(50, 180, 50, 51))
        self.bottom_left_x_dial = QDial(self.frame_7)
        self.bottom_left_x_dial.setObjectName(u"bottom_left_x_dial")
        self.bottom_left_x_dial.setGeometry(QRect(10, 180, 50, 51))
        self.label_32 = QLabel(self.frame_7)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(0, 220, 111, 21))
        self.label_32.setFont(font10)
        self.label_32.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_33 = QLabel(self.frame_7)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(90, 220, 111, 21))
        self.label_33.setFont(font10)
        self.label_33.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.video_keypoints_label = QLabel(self.importVideo)
        self.video_keypoints_label.setObjectName(u"video_keypoints_label")
        self.video_keypoints_label.setGeometry(QRect(490, 10, 471, 281))
        self.video_keypoints_label.setFont(font2)
        self.video_keypoints_label.setFrameShape(QFrame.Shape.WinPanel)
        self.video_keypoints_label.setFrameShadow(QFrame.Shadow.Raised)
        self.video_keypoints_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.frame_3 = QFrame(self.importVideo)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setGeometry(QRect(490, 300, 471, 131))
        self.frame_3.setFrameShape(QFrame.Shape.WinPanel)
        self.frame_3.setFrameShadow(QFrame.Shadow.Raised)
        self.label_16 = QLabel(self.frame_3)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(0, 0, 471, 41))
        font11 = QFont()
        font11.setPointSize(18)
        font11.setBold(True)
        self.label_16.setFont(font11)
        self.label_16.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.tesk_taking_time_chkbox = QCheckBox(self.frame_3)
        self.tesk_taking_time_chkbox.setObjectName(u"tesk_taking_time_chkbox")
        self.tesk_taking_time_chkbox.setGeometry(QRect(10, 30, 241, 31))
        self.tesk_taking_time_chkbox.setFont(font6)
        self.behavior_change_freq_chkbox = QCheckBox(self.frame_3)
        self.behavior_change_freq_chkbox.setObjectName(u"behavior_change_freq_chkbox")
        self.behavior_change_freq_chkbox.setGeometry(QRect(10, 60, 271, 31))
        self.behavior_change_freq_chkbox.setFont(font6)
        self.behavior_count_freq_chkbox = QCheckBox(self.frame_3)
        self.behavior_count_freq_chkbox.setObjectName(u"behavior_count_freq_chkbox")
        self.behavior_count_freq_chkbox.setGeometry(QRect(10, 90, 271, 31))
        self.behavior_count_freq_chkbox.setFont(font6)
        self.frame_4 = QFrame(self.importVideo)
        self.frame_4.setObjectName(u"frame_4")
        self.frame_4.setGeometry(QRect(490, 440, 471, 111))
        self.frame_4.setFrameShape(QFrame.Shape.WinPanel)
        self.frame_4.setFrameShadow(QFrame.Shadow.Raised)
        self.label_17 = QLabel(self.frame_4)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(0, 0, 471, 41))
        self.label_17.setFont(font11)
        self.label_17.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.behavior_count_link_list_chkbox = QCheckBox(self.frame_4)
        self.behavior_count_link_list_chkbox.setObjectName(u"behavior_count_link_list_chkbox")
        self.behavior_count_link_list_chkbox.setGeometry(QRect(10, 30, 371, 31))
        self.behavior_count_link_list_chkbox.setFont(font6)
        self.event_timeline_chkbox = QCheckBox(self.frame_4)
        self.event_timeline_chkbox.setObjectName(u"event_timeline_chkbox")
        self.event_timeline_chkbox.setGeometry(QRect(10, 60, 371, 31))
        self.event_timeline_chkbox.setFont(font6)
        self.frame_5 = QFrame(self.importVideo)
        self.frame_5.setObjectName(u"frame_5")
        self.frame_5.setGeometry(QRect(10, 300, 471, 251))
        self.frame_5.setFrameShape(QFrame.Shape.WinPanel)
        self.frame_5.setFrameShadow(QFrame.Shadow.Raised)
        self.label_15 = QLabel(self.frame_5)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(10, 10, 171, 21))
        font12 = QFont()
        font12.setPointSize(12)
        font12.setItalic(True)
        self.label_15.setFont(font12)
        self.videoDirectory = QLineEdit(self.frame_5)
        self.videoDirectory.setObjectName(u"videoDirectory")
        self.videoDirectory.setGeometry(QRect(10, 40, 331, 31))
        self.videoDirectory.setFont(font9)
        self.videoDirectory.setReadOnly(True)
        self.videoDirectory.setClearButtonEnabled(False)
        self.import_video_button = QPushButton(self.frame_5)
        self.import_video_button.setObjectName(u"import_video_button")
        self.import_video_button.setGeometry(QRect(350, 30, 111, 51))
        font13 = QFont()
        font13.setPointSize(16)
        font13.setBold(False)
        self.import_video_button.setFont(font13)
        self.import_video_button.setAutoFillBackground(False)
        self.analyze_video_button = QPushButton(self.frame_5)
        self.analyze_video_button.setObjectName(u"analyze_video_button")
        self.analyze_video_button.setGeometry(QRect(120, 200, 221, 41))
        font14 = QFont()
        font14.setPointSize(16)
        self.analyze_video_button.setFont(font14)
        self.label_19 = QLabel(self.frame_5)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(10, 140, 101, 16))
        self.label_19.setFont(font3)
        self.label_20 = QLabel(self.frame_5)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(10, 170, 111, 16))
        self.label_20.setFont(font3)
        self.label_21 = QLabel(self.frame_5)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(240, 140, 121, 16))
        self.label_21.setFont(font3)
        self.label_22 = QLabel(self.frame_5)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(240, 170, 141, 16))
        self.label_22.setFont(font3)
        self.importProgressBar = QProgressBar(self.frame_5)
        self.importProgressBar.setObjectName(u"importProgressBar")
        self.importProgressBar.setGeometry(QRect(10, 70, 331, 61))
        self.importProgressBar.setFont(font3)
        self.importProgressBar.setValue(0)
        self.importProgressBar.setAlignment(Qt.AlignmentFlag.AlignBottom|Qt.AlignmentFlag.AlignHCenter)
        self.importProgressBar.setInvertedAppearance(False)
        self.status_import_label = QLabel(self.frame_5)
        self.status_import_label.setObjectName(u"status_import_label")
        self.status_import_label.setGeometry(QRect(350, 85, 111, 41))
        self.status_import_label.setFont(font12)
        self.status_import_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_29 = QLabel(self.importVideo)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(20, 20, 151, 21))
        self.label_29.setFont(font3)
        self.label_29.setAutoFillBackground(True)
        self.label_29.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_30 = QLabel(self.importVideo)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(500, 20, 181, 21))
        self.label_30.setFont(font3)
        self.label_30.setAutoFillBackground(True)
        self.label_30.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.play_pause_button = QPushButton(self.importVideo)
        self.play_pause_button.setObjectName(u"play_pause_button")
        self.play_pause_button.setEnabled(False)
        self.play_pause_button.setGeometry(QRect(400, 250, 71, 31))
        self.play_pause_button.setFont(font3)
        self.showBoundingBoxChkBox = QCheckBox(self.importVideo)
        self.showBoundingBoxChkBox.setObjectName(u"showBoundingBoxChkBox")
        self.showBoundingBoxChkBox.setGeometry(QRect(180, 20, 141, 20))
        self.showKeyPointsChkBox = QCheckBox(self.importVideo)
        self.showKeyPointsChkBox.setObjectName(u"showKeyPointsChkBox")
        self.showKeyPointsChkBox.setGeometry(QRect(690, 20, 131, 20))
        palette = QPalette()
        brush = QBrush(QColor(0, 0, 0, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(255, 255, 255, 107))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        brush2 = QBrush(QColor(255, 255, 255, 135))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush2)
        self.showKeyPointsChkBox.setPalette(palette)
        self.MainTab.addTab(self.importVideo, "")
        self.createDatasetTab = QWidget()
        self.createDatasetTab.setObjectName(u"createDatasetTab")
        self.cameraComboBox = QComboBox(self.createDatasetTab)
        self.cameraComboBox.setObjectName(u"cameraComboBox")
        self.cameraComboBox.setGeometry(QRect(80, 20, 211, 31))
        font15 = QFont()
        font15.setFamilies([u"Segoe UI"])
        font15.setPointSize(14)
        self.cameraComboBox.setFont(font15)
        self.cameraComboBox.setEditable(True)
        self.label_Camera = QLabel(self.createDatasetTab)
        self.label_Camera.setObjectName(u"label_Camera")
        self.label_Camera.setGeometry(QRect(10, 20, 71, 31))
        self.label_Camera.setFont(font15)
        self.openCamera = QPushButton(self.createDatasetTab)
        self.openCamera.setObjectName(u"openCamera")
        self.openCamera.setGeometry(QRect(300, 20, 131, 31))
        font16 = QFont()
        font16.setFamilies([u"Segoe UI"])
        font16.setPointSize(12)
        self.openCamera.setFont(font16)
        self.closeCamera = QPushButton(self.createDatasetTab)
        self.closeCamera.setObjectName(u"closeCamera")
        self.closeCamera.setGeometry(QRect(440, 20, 131, 31))
        self.closeCamera.setFont(font16)
        self.frame = QFrame(self.createDatasetTab)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(10, 70, 911, 481))
        self.frame.setFrameShape(QFrame.Shape.Box)
        self.frame.setFrameShadow(QFrame.Shadow.Sunken)
        self.frame.setLineWidth(2)
        self.camera_feed = QLabel(self.frame)
        self.camera_feed.setObjectName(u"camera_feed")
        self.camera_feed.setGeometry(QRect(10, 10, 441, 242))
        font17 = QFont()
        font17.setFamilies([u"Segoe UI"])
        font17.setPointSize(16)
        font17.setBold(False)
        font17.setItalic(True)
        self.camera_feed.setFont(font17)
        self.camera_feed.setFrameShape(QFrame.Shape.WinPanel)
        self.camera_feed.setFrameShadow(QFrame.Shadow.Raised)
        self.camera_feed.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.white_frame_feed = QLabel(self.frame)
        self.white_frame_feed.setObjectName(u"white_frame_feed")
        self.white_frame_feed.setGeometry(QRect(460, 10, 441, 242))
        self.white_frame_feed.setFont(font17)
        self.white_frame_feed.setFrameShape(QFrame.Shape.WinPanel)
        self.white_frame_feed.setFrameShadow(QFrame.Shadow.Raised)
        self.white_frame_feed.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.darkMode_whiteframe = QCheckBox(self.frame)
        self.darkMode_whiteframe.setObjectName(u"darkMode_whiteframe")
        self.darkMode_whiteframe.setGeometry(QRect(460, 280, 141, 31))
        self.darkMode_whiteframe.setFont(font15)
        self.darkMode_whiteframe.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.show_whiteframe_boundingbox = QCheckBox(self.frame)
        self.show_whiteframe_boundingbox.setObjectName(u"show_whiteframe_boundingbox")
        self.show_whiteframe_boundingbox.setGeometry(QRect(460, 310, 221, 31))
        self.show_whiteframe_boundingbox.setFont(font15)
        self.show_whiteframe_boundingbox.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.showCameraLandmarksChkBox = QCheckBox(self.frame)
        self.showCameraLandmarksChkBox.setObjectName(u"showCameraLandmarksChkBox")
        self.showCameraLandmarksChkBox.setGeometry(QRect(10, 280, 221, 31))
        self.showCameraLandmarksChkBox.setFont(font15)
        self.showCameraLandmarksChkBox.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.showCameraBoundingBoxChkBox = QCheckBox(self.frame)
        self.showCameraBoundingBoxChkBox.setObjectName(u"showCameraBoundingBoxChkBox")
        self.showCameraBoundingBoxChkBox.setGeometry(QRect(10, 310, 191, 31))
        self.showCameraBoundingBoxChkBox.setFont(font15)
        self.showCameraBoundingBoxChkBox.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.label = QLabel(self.frame)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(120, 250, 211, 31))
        font18 = QFont()
        font18.setFamilies([u"Segoe UI"])
        font18.setPointSize(16)
        self.label.setFont(font18)
        self.label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_2 = QLabel(self.frame)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(560, 250, 231, 31))
        self.label_2.setFont(font18)
        self.label_2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.show_skeleton_camera = QCheckBox(self.frame)
        self.show_skeleton_camera.setObjectName(u"show_skeleton_camera")
        self.show_skeleton_camera.setGeometry(QRect(270, 280, 171, 31))
        self.show_skeleton_camera.setFont(font15)
        self.show_skeleton_camera.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.show_skeleton_white_frame = QCheckBox(self.frame)
        self.show_skeleton_white_frame.setObjectName(u"show_skeleton_white_frame")
        self.show_skeleton_white_frame.setGeometry(QRect(720, 280, 171, 31))
        self.show_skeleton_white_frame.setFont(font15)
        self.show_skeleton_white_frame.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.frame_2 = QFrame(self.frame)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(10, 350, 891, 111))
        self.frame_2.setFrameShape(QFrame.Shape.Box)
        self.frame_2.setFrameShadow(QFrame.Shadow.Sunken)
        self.frame_2.setLineWidth(2)
        self.label_4 = QLabel(self.frame_2)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(20, 20, 91, 31))
        self.label_4.setFont(font18)
        self.label_4.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.action_comboBox = QComboBox(self.frame_2)
        self.action_comboBox.setObjectName(u"action_comboBox")
        self.action_comboBox.setGeometry(QRect(120, 20, 271, 31))
        self.action_comboBox.setFont(font15)
        self.action_comboBox.setEditable(True)
        self.add_action_button = QPushButton(self.frame_2)
        self.add_action_button.setObjectName(u"add_action_button")
        self.add_action_button.setGeometry(QRect(120, 60, 121, 31))
        self.add_action_button.setFont(font15)
        self.recording_button = QPushButton(self.frame_2)
        self.recording_button.setObjectName(u"recording_button")
        self.recording_button.setGeometry(QRect(550, 20, 171, 71))
        palette1 = QPalette()
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush3 = QBrush(QColor(170, 255, 127, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Button, brush3)
        brush4 = QBrush(QColor(170, 255, 255, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Light, brush4)
        palette1.setBrush(QPalette.Active, QPalette.Text, brush)
        palette1.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette1.setBrush(QPalette.Active, QPalette.Base, brush3)
        palette1.setBrush(QPalette.Active, QPalette.Window, brush3)
        brush5 = QBrush(QColor(0, 0, 0, 128))
        brush5.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Active, QPalette.PlaceholderText, brush5)
#endif
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Button, brush3)
        brush6 = QBrush(QColor(255, 255, 255, 255))
        brush6.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Inactive, QPalette.Light, brush6)
        palette1.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Base, brush3)
        palette1.setBrush(QPalette.Inactive, QPalette.Window, brush3)
        brush7 = QBrush(QColor(0, 0, 0, 128))
        brush7.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush7)
#endif
        palette1.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.Button, brush3)
        palette1.setBrush(QPalette.Disabled, QPalette.Light, brush6)
        palette1.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.ButtonText, brush2)
        palette1.setBrush(QPalette.Disabled, QPalette.Base, brush3)
        palette1.setBrush(QPalette.Disabled, QPalette.Window, brush3)
        brush8 = QBrush(QColor(0, 0, 0, 128))
        brush8.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush8)
#endif
        self.recording_button.setPalette(palette1)
        font19 = QFont()
        font19.setFamilies([u"Segoe UI"])
        font19.setPointSize(18)
        font19.setBold(True)
        self.recording_button.setFont(font19)
        self.recording_button.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.recording_button.setStyleSheet(u"background-color: rgb(170, 255, 127);\n"
"border-radius: 15px; /* Adjust the radius as needed */\n"
"color: black; /* Set the text color */\n"
"border: 1px solid black; /* Optional: Add a border */")
        self.refresh_button = QPushButton(self.frame_2)
        self.refresh_button.setObjectName(u"refresh_button")
        self.refresh_button.setGeometry(QRect(400, 20, 111, 31))
        self.refresh_button.setFont(font15)
        self.delete_action_button = QPushButton(self.frame_2)
        self.delete_action_button.setObjectName(u"delete_action_button")
        self.delete_action_button.setGeometry(QRect(270, 60, 121, 31))
        self.delete_action_button.setFont(font15)
        self.status_label = QLabel(self.frame)
        self.status_label.setObjectName(u"status_label")
        self.status_label.setGeometry(QRect(70, 20, 131, 21))
        palette2 = QPalette()
        brush9 = QBrush(QColor(0, 255, 0, 255))
        brush9.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.WindowText, brush9)
        palette2.setBrush(QPalette.Active, QPalette.Text, brush9)
        palette2.setBrush(QPalette.Active, QPalette.ButtonText, brush9)
        brush10 = QBrush(QColor(0, 255, 0, 128))
        brush10.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Active, QPalette.PlaceholderText, brush10)
#endif
        palette2.setBrush(QPalette.Inactive, QPalette.WindowText, brush9)
        palette2.setBrush(QPalette.Inactive, QPalette.Text, brush9)
        palette2.setBrush(QPalette.Inactive, QPalette.ButtonText, brush9)
        brush11 = QBrush(QColor(0, 255, 0, 128))
        brush11.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush11)
#endif
        palette2.setBrush(QPalette.Disabled, QPalette.WindowText, brush9)
        palette2.setBrush(QPalette.Disabled, QPalette.Text, brush9)
        palette2.setBrush(QPalette.Disabled, QPalette.ButtonText, brush9)
        brush12 = QBrush(QColor(0, 255, 0, 128))
        brush12.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush12)
#endif
        self.status_label.setPalette(palette2)
        font20 = QFont()
        font20.setFamilies([u"Segoe UI"])
        font20.setPointSize(12)
        font20.setBold(True)
        self.status_label.setFont(font20)
        self.status_label.setStyleSheet(u"color: rgb(0, 255, 0);")
        self.status_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.label_12 = QLabel(self.frame)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(20, 20, 51, 21))
        self.label_12.setFont(font16)
        self.label_12.setAutoFillBackground(True)
        self.line_5 = QFrame(self.frame)
        self.line_5.setObjectName(u"line_5")
        self.line_5.setGeometry(QRect(10, 455, 891, 31))
        self.line_5.setFrameShape(QFrame.Shape.HLine)
        self.line_5.setFrameShadow(QFrame.Shadow.Sunken)
        self.groupBox = QGroupBox(self.createDatasetTab)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(930, 60, 261, 491))
        font21 = QFont()
        font21.setFamilies([u"Segoe UI"])
        font21.setPointSize(16)
        font21.setBold(True)
        self.groupBox.setFont(font21)
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setStyleSheet(u"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:2 rgba(255, 255, 255, 255));")
        self.groupBox.setFlat(False)
        self.label_3 = QLabel(self.groupBox)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 40, 121, 21))
        self.label_3.setFont(font16)
        self.directoryLineEdit = QLineEdit(self.groupBox)
        self.directoryLineEdit.setObjectName(u"directoryLineEdit")
        self.directoryLineEdit.setGeometry(QRect(20, 70, 221, 31))
        font22 = QFont()
        font22.setFamilies([u"Segoe UI"])
        font22.setPointSize(10)
        font22.setItalic(True)
        self.directoryLineEdit.setFont(font22)
        self.browseButton = QPushButton(self.groupBox)
        self.browseButton.setObjectName(u"browseButton")
        self.browseButton.setGeometry(QRect(90, 110, 91, 31))
        font23 = QFont()
        font23.setFamilies([u"Segoe UI"])
        font23.setPointSize(11)
        self.browseButton.setFont(font23)
        self.refresh_action_list = QPushButton(self.groupBox)
        self.refresh_action_list.setObjectName(u"refresh_action_list")
        self.refresh_action_list.setGeometry(QRect(90, 310, 91, 31))
        self.refresh_action_list.setFont(font)
        self.action_table = QTableWidget(self.groupBox)
        if (self.action_table.columnCount() < 2):
            self.action_table.setColumnCount(2)
        if (self.action_table.rowCount() < 7):
            self.action_table.setRowCount(7)
        self.action_table.setObjectName(u"action_table")
        self.action_table.setGeometry(QRect(10, 150, 241, 151))
        self.action_table.setFrameShape(QFrame.Shape.WinPanel)
        self.action_table.setFrameShadow(QFrame.Shadow.Raised)
        self.action_table.setLineWidth(2)
        self.action_table.setAutoScrollMargin(9)
        self.action_table.setProperty(u"showDropIndicator", False)
        self.action_table.setDragEnabled(False)
        self.action_table.setDragDropOverwriteMode(False)
        self.action_table.setShowGrid(True)
        self.action_table.setGridStyle(Qt.PenStyle.SolidLine)
        self.action_table.setSortingEnabled(False)
        self.action_table.setWordWrap(True)
        self.action_table.setCornerButtonEnabled(False)
        self.action_table.setRowCount(7)
        self.action_table.setColumnCount(2)
        self.action_table.horizontalHeader().setCascadingSectionResizes(False)
        self.action_table.horizontalHeader().setMinimumSectionSize(37)
        self.action_table.horizontalHeader().setDefaultSectionSize(111)
        self.action_table.horizontalHeader().setProperty(u"showSortIndicator", False)
        self.action_table.verticalHeader().setVisible(False)
        self.action_table.verticalHeader().setDefaultSectionSize(25)
        self.interval_slider = QSlider(self.groupBox)
        self.interval_slider.setObjectName(u"interval_slider")
        self.interval_slider.setGeometry(QRect(10, 370, 171, 21))
        self.interval_slider.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.interval_slider.setMinimum(1)
        self.interval_slider.setMaximum(10)
        self.interval_slider.setSliderPosition(3)
        self.interval_slider.setOrientation(Qt.Orientation.Horizontal)
        self.interval_slider.setTickPosition(QSlider.TickPosition.TicksAbove)
        self.interval_label = QLabel(self.groupBox)
        self.interval_label.setObjectName(u"interval_label")
        self.interval_label.setGeometry(QRect(200, 360, 41, 41))
        self.interval_label.setFont(font19)
        self.interval_label.setStyleSheet(u"border-color: rgb(0, 0, 0);\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.interval_label.setFrameShape(QFrame.Shape.Box)
        self.interval_label.setFrameShadow(QFrame.Shadow.Sunken)
        self.interval_label.setLineWidth(1)
        self.interval_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.interval_label.setMargin(0)
        self.label_8 = QLabel(self.groupBox)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 350, 151, 21))
        font24 = QFont()
        font24.setFamilies([u"Segoe UI"])
        font24.setPointSize(12)
        font24.setBold(False)
        self.label_8.setFont(font24)
        self.label_8.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.sequence_label = QLabel(self.groupBox)
        self.sequence_label.setObjectName(u"sequence_label")
        self.sequence_label.setGeometry(QRect(200, 430, 41, 41))
        self.sequence_label.setFont(font19)
        self.sequence_label.setStyleSheet(u"border-color: rgb(0, 0, 0);\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.sequence_label.setFrameShape(QFrame.Shape.Box)
        self.sequence_label.setFrameShadow(QFrame.Shadow.Sunken)
        self.sequence_label.setLineWidth(1)
        self.sequence_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.sequence_label.setMargin(0)
        self.sequence_slider = QSlider(self.groupBox)
        self.sequence_slider.setObjectName(u"sequence_slider")
        self.sequence_slider.setGeometry(QRect(10, 440, 171, 21))
        self.sequence_slider.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.sequence_slider.setMinimum(1)
        self.sequence_slider.setMaximum(60)
        self.sequence_slider.setValue(30)
        self.sequence_slider.setSliderPosition(30)
        self.sequence_slider.setOrientation(Qt.Orientation.Horizontal)
        self.sequence_slider.setTickPosition(QSlider.TickPosition.TicksAbove)
        self.label_11 = QLabel(self.groupBox)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(10, 410, 171, 21))
        self.label_11.setFont(font3)
        self.label_11.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.label_5 = QLabel(self.createDatasetTab)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(790, 10, 81, 16))
        font25 = QFont()
        font25.setFamilies([u"Segoe UI"])
        font25.setPointSize(10)
        self.label_5.setFont(font25)
        self.cpu_label = QLabel(self.createDatasetTab)
        self.cpu_label.setObjectName(u"cpu_label")
        self.cpu_label.setGeometry(QRect(790, 20, 91, 41))
        palette3 = QPalette()
        brush13 = QBrush(QColor(0, 85, 255, 255))
        brush13.setStyle(Qt.SolidPattern)
        palette3.setBrush(QPalette.Active, QPalette.WindowText, brush13)
        palette3.setBrush(QPalette.Inactive, QPalette.WindowText, brush13)
        brush14 = QBrush(QColor(120, 120, 120, 255))
        brush14.setStyle(Qt.SolidPattern)
        palette3.setBrush(QPalette.Disabled, QPalette.WindowText, brush14)
        self.cpu_label.setPalette(palette3)
        font26 = QFont()
        font26.setFamilies([u"Segoe UI"])
        font26.setPointSize(20)
        font26.setBold(True)
        self.cpu_label.setFont(font26)
        self.ram_label = QLabel(self.createDatasetTab)
        self.ram_label.setObjectName(u"ram_label")
        self.ram_label.setGeometry(QRect(930, 20, 91, 41))
        palette4 = QPalette()
        brush15 = QBrush(QColor(170, 0, 0, 255))
        brush15.setStyle(Qt.SolidPattern)
        palette4.setBrush(QPalette.Active, QPalette.WindowText, brush15)
        palette4.setBrush(QPalette.Inactive, QPalette.WindowText, brush15)
        palette4.setBrush(QPalette.Disabled, QPalette.WindowText, brush14)
        self.ram_label.setPalette(palette4)
        self.ram_label.setFont(font26)
        self.label_9 = QLabel(self.createDatasetTab)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(1060, 10, 81, 16))
        self.label_9.setFont(font25)
        self.gpu_label = QLabel(self.createDatasetTab)
        self.gpu_label.setObjectName(u"gpu_label")
        self.gpu_label.setGeometry(QRect(1060, 20, 91, 41))
        palette5 = QPalette()
        brush16 = QBrush(QColor(85, 170, 0, 255))
        brush16.setStyle(Qt.SolidPattern)
        palette5.setBrush(QPalette.Active, QPalette.WindowText, brush16)
        palette5.setBrush(QPalette.Inactive, QPalette.WindowText, brush16)
        palette5.setBrush(QPalette.Disabled, QPalette.WindowText, brush14)
        self.gpu_label.setPalette(palette5)
        self.gpu_label.setFont(font26)
        self.label_10 = QLabel(self.createDatasetTab)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(670, 10, 51, 21))
        self.label_10.setFont(font25)
        self.fps_label = QLabel(self.createDatasetTab)
        self.fps_label.setObjectName(u"fps_label")
        self.fps_label.setGeometry(QRect(670, 20, 91, 41))
        palette6 = QPalette()
        brush17 = QBrush(QColor(170, 85, 255, 255))
        brush17.setStyle(Qt.SolidPattern)
        palette6.setBrush(QPalette.Active, QPalette.WindowText, brush17)
        palette6.setBrush(QPalette.Inactive, QPalette.WindowText, brush17)
        palette6.setBrush(QPalette.Disabled, QPalette.WindowText, brush14)
        self.fps_label.setPalette(palette6)
        self.fps_label.setFont(font26)
        self.label_6 = QLabel(self.createDatasetTab)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(930, 10, 81, 16))
        self.label_6.setFont(font25)
        self.MainTab.addTab(self.createDatasetTab, "")
        self.label_18 = QLabel(self.centralwidget)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(840, 0, 351, 91))
        font27 = QFont()
        font27.setFamilies([u"Gabriola"])
        font27.setPointSize(60)
        self.label_18.setFont(font27)
        self.label_18.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTop|Qt.AlignmentFlag.AlignTrailing)
        self.timeLCD = QLCDNumber(self.centralwidget)
        self.timeLCD.setObjectName(u"timeLCD")
        self.timeLCD.setGeometry(QRect(740, 10, 161, 51))
        self.timeLCD.setFont(font7)
        self.timeLCD.setAutoFillBackground(True)
        self.timeLCD.setFrameShadow(QFrame.Shadow.Sunken)
        self.timeLCD.setLineWidth(1)
        self.timeLCD.setMidLineWidth(0)
        self.timeLCD.setDigitCount(8)
        self.timeLCD.setSegmentStyle(QLCDNumber.SegmentStyle.Filled)
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(700, 0, 31, 31))
        self.label_7.setFont(font25)
        self.date_label = QLabel(self.centralwidget)
        self.date_label.setObjectName(u"date_label")
        self.date_label.setGeometry(QRect(510, 0, 131, 31))
        self.date_label.setFont(font25)
        self.day_label = QLabel(self.centralwidget)
        self.day_label.setObjectName(u"day_label")
        self.day_label.setGeometry(QRect(510, 20, 191, 41))
        font28 = QFont()
        font28.setFamilies([u"Segoe UI"])
        font28.setPointSize(20)
        font28.setItalic(False)
        self.day_label.setFont(font28)
        self.line = QFrame(self.centralwidget)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(10, -20, 481, 61))
        self.line.setLineWidth(1)
        self.line.setFrameShape(QFrame.Shape.HLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_2 = QFrame(self.centralwidget)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(473, 10, 41, 51))
        self.line_2.setLineWidth(1)
        self.line_2.setFrameShape(QFrame.Shape.VLine)
        self.line_2.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_3 = QFrame(self.centralwidget)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(930, 10, 118, 3))
        self.line_3.setFrameShape(QFrame.Shape.HLine)
        self.line_3.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_4 = QFrame(self.centralwidget)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(1090, 0, 91, 31))
        self.line_4.setFrameShape(QFrame.Shape.HLine)
        self.line_4.setFrameShadow(QFrame.Shadow.Sunken)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1198, 33))
        self.menuARMIS = QMenu(self.menubar)
        self.menuARMIS.setObjectName(u"menuARMIS")
        self.menuARMIS.setStyleSheet(u"border-color: rgb(0, 0, 0);")
        self.menuARMIS.setTearOffEnabled(False)
        self.menuARMIS.setSeparatorsCollapsible(False)
        self.menuView = QMenu(self.menubar)
        self.menuView.setObjectName(u"menuView")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuARMIS.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menuARMIS.addAction(self.fileNew)
        self.menuARMIS.addAction(self.fileOpen)
        self.menuARMIS.addAction(self.fileSave)
        self.menuARMIS.addAction(self.fileExport)
        self.menuARMIS.addAction(self.fileExit)
        self.menuView.addAction(self.actionviewCreateDataset)

        self.retranslateUi(MainWindow)

        self.MainTab.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Pose Estimation Analytics", None))
        self.fileNew.setText(QCoreApplication.translate("MainWindow", u"New", None))
        self.fileOpen.setText(QCoreApplication.translate("MainWindow", u"Open", None))
        self.fileSave.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.fileExport.setText(QCoreApplication.translate("MainWindow", u"Export", None))
        self.fileExit.setText(QCoreApplication.translate("MainWindow", u"Exit", None))
        self.actionviewCreateDataset.setText(QCoreApplication.translate("MainWindow", u"View Create Dataset Tab", None))
        self.video_preview_label.setText(QCoreApplication.translate("MainWindow", u"Import a video to see preview", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"Advanced Options", None))
        self.label_34.setText(QCoreApplication.translate("MainWindow", u"Confidence Rate:\n"
"(Human Detection)", None))
        self.confLineEdit.setText(QCoreApplication.translate("MainWindow", u"100", None))
        self.label_35.setText(QCoreApplication.translate("MainWindow", u"%", None))
        self.label_36.setText(QCoreApplication.translate("MainWindow", u"FPS Loading Rate:", None))
        self.label_37.setText(QCoreApplication.translate("MainWindow", u"%", None))
        self.fpsLoadingRateLineEdit.setText(QCoreApplication.translate("MainWindow", u"100", None))
        self.label_38.setText(QCoreApplication.translate("MainWindow", u"Confidence Rate:\n"
"(Human Pose)", None))
        self.label_39.setText(QCoreApplication.translate("MainWindow", u"%", None))
        self.confLineEdit_2.setText(QCoreApplication.translate("MainWindow", u"100", None))
        self.show_2.setText(QCoreApplication.translate("MainWindow", u"Refresh Detections", None))
        self.label_23.setText(QCoreApplication.translate("MainWindow", u"Top Left", None))
        self.label_24.setText(QCoreApplication.translate("MainWindow", u"Top Right", None))
        self.label_27.setText(QCoreApplication.translate("MainWindow", u"Classroom Reference\n"
"Points", None))
        self.label_25.setText(QCoreApplication.translate("MainWindow", u"Bottom Right", None))
        self.label_26.setText(QCoreApplication.translate("MainWindow", u"Bottom Left", None))
        self.label_28.setText(QCoreApplication.translate("MainWindow", u"x         y", None))
        self.label_31.setText(QCoreApplication.translate("MainWindow", u"x         y", None))
        self.label_32.setText(QCoreApplication.translate("MainWindow", u"x         y", None))
        self.label_33.setText(QCoreApplication.translate("MainWindow", u"x         y", None))
        self.video_keypoints_label.setText(QCoreApplication.translate("MainWindow", u"Import a video to see preview", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"Classroom Heatmap View", None))
        self.tesk_taking_time_chkbox.setText(QCoreApplication.translate("MainWindow", u"Test-Taking Time Duration", None))
        self.behavior_change_freq_chkbox.setText(QCoreApplication.translate("MainWindow", u"Behavior Change Frequencies", None))
        self.behavior_count_freq_chkbox.setText(QCoreApplication.translate("MainWindow", u"Behavior Count Frequencies", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"Other Visualizations", None))
        self.behavior_count_link_list_chkbox.setText(QCoreApplication.translate("MainWindow", u"Behavior Count Frequencies [Linked List]", None))
        self.event_timeline_chkbox.setText(QCoreApplication.translate("MainWindow", u"Event Timeline", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Video File Location:", None))
        self.videoDirectory.setText(QCoreApplication.translate("MainWindow", u"Import a video file to be analyzed.", None))
        self.videoDirectory.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Find a video file", None))
        self.import_video_button.setText(QCoreApplication.translate("MainWindow", u"Browse", None))
        self.analyze_video_button.setText(QCoreApplication.translate("MainWindow", u"Get Analytics", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"File name:", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"Video Duration:", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"File Size:", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"Frame Dimensions:", None))
        self.status_import_label.setText(QCoreApplication.translate("MainWindow", u"[ IMPORT A \n"
"VIDEO ]", None))
        self.label_29.setText(QCoreApplication.translate("MainWindow", u"Video File Preview", None))
        self.label_30.setText(QCoreApplication.translate("MainWindow", u"  Detections Visualization", None))
        self.play_pause_button.setText(QCoreApplication.translate("MainWindow", u"PLAY", None))
        self.showBoundingBoxChkBox.setText(QCoreApplication.translate("MainWindow", u"Show Bounding Boxes", None))
        self.showKeyPointsChkBox.setText(QCoreApplication.translate("MainWindow", u"Show Keypoints", None))
        self.MainTab.setTabText(self.MainTab.indexOf(self.importVideo), QCoreApplication.translate("MainWindow", u"Import Video", None))
        self.label_Camera.setText(QCoreApplication.translate("MainWindow", u"Camera", None))
        self.openCamera.setText(QCoreApplication.translate("MainWindow", u"Open Camera", None))
        self.closeCamera.setText(QCoreApplication.translate("MainWindow", u"Close Camera", None))
        self.camera_feed.setText(QCoreApplication.translate("MainWindow", u"Camera Feed will show here", None))
        self.white_frame_feed.setText(QCoreApplication.translate("MainWindow", u"Body Pose Key Points will show here", None))
        self.darkMode_whiteframe.setText(QCoreApplication.translate("MainWindow", u"Dark Mode", None))
        self.show_whiteframe_boundingbox.setText(QCoreApplication.translate("MainWindow", u"Show Bounding Boxes", None))
        self.showCameraLandmarksChkBox.setText(QCoreApplication.translate("MainWindow", u"Show Body Landmarks", None))
        self.showCameraBoundingBoxChkBox.setText(QCoreApplication.translate("MainWindow", u"Show Bounding Box", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Camera Feed", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Key Points Visualization", None))
        self.show_skeleton_camera.setText(QCoreApplication.translate("MainWindow", u"Show in Skeleton", None))
        self.show_skeleton_white_frame.setText(QCoreApplication.translate("MainWindow", u"Show in Skeleton", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"ACTION:", None))
        self.add_action_button.setText(QCoreApplication.translate("MainWindow", u"Add Action", None))
        self.recording_button.setText(QCoreApplication.translate("MainWindow", u"START\n"
"RECORDING", None))
        self.refresh_button.setText(QCoreApplication.translate("MainWindow", u"Refresh", None))
        self.delete_action_button.setText(QCoreApplication.translate("MainWindow", u"Delete", None))
        self.status_label.setText(QCoreApplication.translate("MainWindow", u"NOT RECORDING", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Status:", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Dataset Details", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Folder Location", None))
        self.browseButton.setText(QCoreApplication.translate("MainWindow", u"Browse", None))
        self.refresh_action_list.setText(QCoreApplication.translate("MainWindow", u"Refresh", None))
        self.interval_label.setText(QCoreApplication.translate("MainWindow", u"--", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Break Interval Length", None))
        self.sequence_label.setText(QCoreApplication.translate("MainWindow", u"--", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"No. of Frames per Video", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"CPU Usage", None))
        self.cpu_label.setText(QCoreApplication.translate("MainWindow", u"--", None))
        self.ram_label.setText(QCoreApplication.translate("MainWindow", u"--", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"GPU Usage", None))
        self.gpu_label.setText(QCoreApplication.translate("MainWindow", u"--", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"FPS:", None))
        self.fps_label.setText(QCoreApplication.translate("MainWindow", u"--", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"RAM Usage", None))
        self.MainTab.setTabText(self.MainTab.indexOf(self.createDatasetTab), QCoreApplication.translate("MainWindow", u"Create Dataset", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"LearnScope", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Time:", None))
        self.date_label.setText(QCoreApplication.translate("MainWindow", u"Today is:", None))
        self.day_label.setText(QCoreApplication.translate("MainWindow", u"--", None))
        self.menuARMIS.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuView.setTitle(QCoreApplication.translate("MainWindow", u"View", None))
    # retranslateUi

