# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Design 1ZJRHtK.ui'
##
## Created by: Qt User Interface Compiler version 5.14.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1204, 787)
        self.actionExit = QAction(MainWindow)
        self.actionExit.setObjectName(u"actionExit")
        self.actionOpen = QAction(MainWindow)
        self.actionOpen.setObjectName(u"actionOpen")
        self.actionSave = QAction(MainWindow)
        self.actionSave.setObjectName(u"actionSave")
        self.actionExport = QAction(MainWindow)
        self.actionExport.setObjectName(u"actionExport")
        self.actionExit_2 = QAction(MainWindow)
        self.actionExit_2.setObjectName(u"actionExit_2")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.MainTab = QTabWidget(self.centralwidget)
        self.MainTab.setObjectName(u"MainTab")
        self.MainTab.setGeometry(QRect(0, 0, 1200, 671))
        font = QFont()
        font.setFamily(u"Segoe UI")
        font.setPointSize(18)
        self.MainTab.setFont(font)
        self.MainTab.setTabPosition(QTabWidget.North)
        self.MainTab.setTabShape(QTabWidget.Rounded)
        self.MainTab.setIconSize(QSize(16, 16))
        self.MainTab.setElideMode(Qt.ElideNone)
        self.analyticstTab = QWidget()
        self.analyticstTab.setObjectName(u"analyticstTab")
        self.MainTab.addTab(self.analyticstTab, "")
        self.createDatasetTab = QWidget()
        self.createDatasetTab.setObjectName(u"createDatasetTab")
        self.cameraComboBox = QComboBox(self.createDatasetTab)
        self.cameraComboBox.setObjectName(u"cameraComboBox")
        self.cameraComboBox.setGeometry(QRect(80, 20, 211, 31))
        font1 = QFont()
        font1.setPointSize(14)
        self.cameraComboBox.setFont(font1)
        self.cameraComboBox.setEditable(True)
        self.label_Camera = QLabel(self.createDatasetTab)
        self.label_Camera.setObjectName(u"label_Camera")
        self.label_Camera.setGeometry(QRect(10, 20, 71, 31))
        self.label_Camera.setFont(font1)
        self.openCamera = QPushButton(self.createDatasetTab)
        self.openCamera.setObjectName(u"openCamera")
        self.openCamera.setGeometry(QRect(300, 20, 131, 31))
        font2 = QFont()
        font2.setPointSize(12)
        self.openCamera.setFont(font2)
        self.closeCamera = QPushButton(self.createDatasetTab)
        self.closeCamera.setObjectName(u"closeCamera")
        self.closeCamera.setGeometry(QRect(440, 20, 131, 31))
        self.closeCamera.setFont(font2)
        self.frame = QFrame(self.createDatasetTab)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(10, 70, 901, 551))
        self.frame.setFrameShape(QFrame.Box)
        self.frame.setFrameShadow(QFrame.Sunken)
        self.frame.setLineWidth(2)
        self.camera_feed = QLabel(self.frame)
        self.camera_feed.setObjectName(u"camera_feed")
        self.camera_feed.setGeometry(QRect(10, 10, 431, 242))
        font3 = QFont()
        font3.setPointSize(16)
        font3.setBold(False)
        font3.setItalic(True)
        font3.setWeight(50)
        self.camera_feed.setFont(font3)
        self.camera_feed.setFrameShape(QFrame.Box)
        self.camera_feed.setFrameShadow(QFrame.Sunken)
        self.camera_feed.setAlignment(Qt.AlignCenter)
        self.white_frame_feed = QLabel(self.frame)
        self.white_frame_feed.setObjectName(u"white_frame_feed")
        self.white_frame_feed.setGeometry(QRect(460, 10, 431, 242))
        self.white_frame_feed.setFont(font3)
        self.white_frame_feed.setFrameShape(QFrame.Box)
        self.white_frame_feed.setFrameShadow(QFrame.Sunken)
        self.white_frame_feed.setAlignment(Qt.AlignCenter)
        self.darkMode_whiteframe = QCheckBox(self.frame)
        self.darkMode_whiteframe.setObjectName(u"darkMode_whiteframe")
        self.darkMode_whiteframe.setGeometry(QRect(460, 280, 141, 31))
        self.darkMode_whiteframe.setFont(font1)
        self.darkMode_whiteframe.setCursor(QCursor(Qt.PointingHandCursor))
        self.show_whiteframe_boundingbox = QCheckBox(self.frame)
        self.show_whiteframe_boundingbox.setObjectName(u"show_whiteframe_boundingbox")
        self.show_whiteframe_boundingbox.setGeometry(QRect(460, 310, 221, 31))
        self.show_whiteframe_boundingbox.setFont(font1)
        self.show_whiteframe_boundingbox.setCursor(QCursor(Qt.PointingHandCursor))
        self.showCameraLandmarksChkBox = QCheckBox(self.frame)
        self.showCameraLandmarksChkBox.setObjectName(u"showCameraLandmarksChkBox")
        self.showCameraLandmarksChkBox.setGeometry(QRect(10, 280, 221, 31))
        self.showCameraLandmarksChkBox.setFont(font1)
        self.showCameraLandmarksChkBox.setCursor(QCursor(Qt.PointingHandCursor))
        self.showCameraBoundingBoxChkBox = QCheckBox(self.frame)
        self.showCameraBoundingBoxChkBox.setObjectName(u"showCameraBoundingBoxChkBox")
        self.showCameraBoundingBoxChkBox.setGeometry(QRect(10, 310, 191, 31))
        self.showCameraBoundingBoxChkBox.setFont(font1)
        self.showCameraBoundingBoxChkBox.setCursor(QCursor(Qt.PointingHandCursor))
        self.label = QLabel(self.frame)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(120, 250, 211, 31))
        font4 = QFont()
        font4.setPointSize(16)
        self.label.setFont(font4)
        self.label.setAlignment(Qt.AlignCenter)
        self.label_2 = QLabel(self.frame)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(560, 250, 231, 31))
        self.label_2.setFont(font4)
        self.label_2.setAlignment(Qt.AlignCenter)
        self.show_skeleton_camera = QCheckBox(self.frame)
        self.show_skeleton_camera.setObjectName(u"show_skeleton_camera")
        self.show_skeleton_camera.setGeometry(QRect(270, 280, 171, 31))
        self.show_skeleton_camera.setFont(font1)
        self.show_skeleton_camera.setCursor(QCursor(Qt.PointingHandCursor))
        self.show_skeleton_white_frame = QCheckBox(self.frame)
        self.show_skeleton_white_frame.setObjectName(u"show_skeleton_white_frame")
        self.show_skeleton_white_frame.setGeometry(QRect(720, 280, 171, 31))
        self.show_skeleton_white_frame.setFont(font1)
        self.show_skeleton_white_frame.setCursor(QCursor(Qt.PointingHandCursor))
        self.frame_2 = QFrame(self.frame)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(10, 350, 881, 191))
        self.frame_2.setFrameShape(QFrame.Box)
        self.frame_2.setFrameShadow(QFrame.Sunken)
        self.frame_2.setLineWidth(2)
        self.label_4 = QLabel(self.frame_2)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(20, 20, 91, 31))
        self.label_4.setFont(font4)
        self.label_4.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.action_comboBox = QComboBox(self.frame_2)
        self.action_comboBox.setObjectName(u"action_comboBox")
        self.action_comboBox.setGeometry(QRect(140, 20, 231, 31))
        self.action_comboBox.setFont(font1)
        self.action_comboBox.setEditable(True)
        self.add_action_button = QPushButton(self.frame_2)
        self.add_action_button.setObjectName(u"add_action_button")
        self.add_action_button.setGeometry(QRect(140, 60, 111, 31))
        self.add_action_button.setFont(font1)
        self.start_recording_button = QPushButton(self.frame_2)
        self.start_recording_button.setObjectName(u"start_recording_button")
        self.start_recording_button.setGeometry(QRect(500, 10, 181, 161))
        palette = QPalette()
        brush = QBrush(QColor(0, 0, 0, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(170, 255, 127, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        brush2 = QBrush(QColor(170, 255, 255, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        brush3 = QBrush(QColor(255, 255, 255, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Light, brush3)
        brush4 = QBrush(QColor(120, 120, 120, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Light, brush3)
        self.start_recording_button.setPalette(palette)
        self.start_recording_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.horizontalSlider = QSlider(self.frame_2)
        self.horizontalSlider.setObjectName(u"horizontalSlider")
        self.horizontalSlider.setGeometry(QRect(140, 110, 231, 51))
        self.horizontalSlider.setCursor(QCursor(Qt.PointingHandCursor))
        self.horizontalSlider.setMinimum(1)
        self.horizontalSlider.setMaximum(10)
        self.horizontalSlider.setSliderPosition(3)
        self.horizontalSlider.setOrientation(Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QSlider.TicksAbove)
        self.label_8 = QLabel(self.frame_2)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(20, 110, 121, 51))
        self.label_8.setFont(font4)
        self.label_8.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.refresh_button = QPushButton(self.frame_2)
        self.refresh_button.setObjectName(u"refresh_button")
        self.refresh_button.setGeometry(QRect(380, 20, 111, 31))
        self.refresh_button.setFont(font1)
        self.start_recording_button_2 = QPushButton(self.frame_2)
        self.start_recording_button_2.setObjectName(u"start_recording_button_2")
        self.start_recording_button_2.setGeometry(QRect(690, 10, 181, 161))
        palette1 = QPalette()
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette1.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Light, brush3)
        palette1.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette1.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.Light, brush3)
        self.start_recording_button_2.setPalette(palette1)
        self.start_recording_button_2.setCursor(QCursor(Qt.PointingHandCursor))
        self.delete_action_button = QPushButton(self.frame_2)
        self.delete_action_button.setObjectName(u"delete_action_button")
        self.delete_action_button.setGeometry(QRect(260, 60, 111, 31))
        self.delete_action_button.setFont(font1)
        self.groupBox = QGroupBox(self.createDatasetTab)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(920, 60, 261, 561))
        font5 = QFont()
        font5.setFamily(u"Segoe UI")
        font5.setPointSize(16)
        font5.setBold(True)
        font5.setWeight(75)
        self.groupBox.setFont(font5)
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setStyleSheet(u"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:2 rgba(255, 255, 255, 255));")
        self.groupBox.setFlat(False)
        self.label_3 = QLabel(self.groupBox)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 40, 121, 21))
        font6 = QFont()
        font6.setFamily(u"Segoe UI")
        font6.setPointSize(12)
        self.label_3.setFont(font6)
        self.directoryLineEdit = QLineEdit(self.groupBox)
        self.directoryLineEdit.setObjectName(u"directoryLineEdit")
        self.directoryLineEdit.setGeometry(QRect(20, 70, 221, 31))
        font7 = QFont()
        font7.setFamily(u"Segoe UI")
        font7.setPointSize(10)
        font7.setItalic(True)
        self.directoryLineEdit.setFont(font7)
        self.browseButton = QPushButton(self.groupBox)
        self.browseButton.setObjectName(u"browseButton")
        self.browseButton.setGeometry(QRect(90, 110, 91, 31))
        font8 = QFont()
        font8.setFamily(u"Segoe UI")
        font8.setPointSize(11)
        self.browseButton.setFont(font8)
        self.tableView = QTableView(self.groupBox)
        self.tableView.setObjectName(u"tableView")
        self.tableView.setGeometry(QRect(10, 150, 241, 192))
        self.label_5 = QLabel(self.createDatasetTab)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(610, 10, 81, 16))
        font9 = QFont()
        font9.setPointSize(10)
        self.label_5.setFont(font9)
        self.label_6 = QLabel(self.createDatasetTab)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(720, 10, 81, 16))
        self.label_6.setFont(font9)
        self.cpu_label = QLabel(self.createDatasetTab)
        self.cpu_label.setObjectName(u"cpu_label")
        self.cpu_label.setGeometry(QRect(610, 20, 91, 41))
        palette2 = QPalette()
        brush5 = QBrush(QColor(0, 85, 255, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.WindowText, brush5)
        palette2.setBrush(QPalette.Inactive, QPalette.WindowText, brush5)
        palette2.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        self.cpu_label.setPalette(palette2)
        font10 = QFont()
        font10.setPointSize(20)
        font10.setBold(True)
        font10.setWeight(75)
        self.cpu_label.setFont(font10)
        self.ram_label = QLabel(self.createDatasetTab)
        self.ram_label.setObjectName(u"ram_label")
        self.ram_label.setGeometry(QRect(720, 20, 91, 41))
        palette3 = QPalette()
        brush6 = QBrush(QColor(170, 0, 0, 255))
        brush6.setStyle(Qt.SolidPattern)
        palette3.setBrush(QPalette.Active, QPalette.WindowText, brush6)
        palette3.setBrush(QPalette.Inactive, QPalette.WindowText, brush6)
        palette3.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        self.ram_label.setPalette(palette3)
        self.ram_label.setFont(font10)
        self.timeLCD = QLCDNumber(self.createDatasetTab)
        self.timeLCD.setObjectName(u"timeLCD")
        self.timeLCD.setGeometry(QRect(1010, 20, 171, 41))
        self.timeLCD.setLineWidth(1)
        self.timeLCD.setMidLineWidth(0)
        self.timeLCD.setDigitCount(8)
        self.timeLCD.setSegmentStyle(QLCDNumber.Filled)
        self.label_7 = QLabel(self.createDatasetTab)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(1010, 0, 51, 21))
        self.label_7.setFont(font9)
        self.label_9 = QLabel(self.createDatasetTab)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(830, 10, 81, 16))
        self.label_9.setFont(font9)
        self.gpu_label = QLabel(self.createDatasetTab)
        self.gpu_label.setObjectName(u"gpu_label")
        self.gpu_label.setGeometry(QRect(830, 20, 91, 41))
        palette4 = QPalette()
        brush7 = QBrush(QColor(85, 170, 0, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette4.setBrush(QPalette.Active, QPalette.WindowText, brush7)
        palette4.setBrush(QPalette.Inactive, QPalette.WindowText, brush7)
        palette4.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        self.gpu_label.setPalette(palette4)
        self.gpu_label.setFont(font10)
        self.MainTab.addTab(self.createDatasetTab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1204, 21))
        self.menuARMIS = QMenu(self.menubar)
        self.menuARMIS.setObjectName(u"menuARMIS")
        self.menuView = QMenu(self.menubar)
        self.menuView.setObjectName(u"menuView")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuARMIS.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menuARMIS.addAction(self.actionExit)
        self.menuARMIS.addAction(self.actionOpen)
        self.menuARMIS.addAction(self.actionSave)
        self.menuARMIS.addAction(self.actionExport)
        self.menuARMIS.addAction(self.actionExit_2)

        self.retranslateUi(MainWindow)

        self.MainTab.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionExit.setText(QCoreApplication.translate("MainWindow", u"New", None))
        self.actionOpen.setText(QCoreApplication.translate("MainWindow", u"Open", None))
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.actionExport.setText(QCoreApplication.translate("MainWindow", u"Export", None))
        self.actionExit_2.setText(QCoreApplication.translate("MainWindow", u"Exit", None))
        self.MainTab.setTabText(self.MainTab.indexOf(self.analyticstTab), QCoreApplication.translate("MainWindow", u"Analytics", None))
        self.label_Camera.setText(QCoreApplication.translate("MainWindow", u"Camera", None))
        self.openCamera.setText(QCoreApplication.translate("MainWindow", u"Open Camera", None))
        self.closeCamera.setText(QCoreApplication.translate("MainWindow", u"Close Camera", None))
        self.camera_feed.setText(QCoreApplication.translate("MainWindow", u"Camera Feed will show here", None))
        self.white_frame_feed.setText(QCoreApplication.translate("MainWindow", u"Body Pose Key Points will show here", None))
        self.darkMode_whiteframe.setText(QCoreApplication.translate("MainWindow", u"Dark Mode", None))
        self.show_whiteframe_boundingbox.setText(QCoreApplication.translate("MainWindow", u"Show Bounding Boxes", None))
        self.showCameraLandmarksChkBox.setText(QCoreApplication.translate("MainWindow", u"Show Body Landmarks", None))
        self.showCameraBoundingBoxChkBox.setText(QCoreApplication.translate("MainWindow", u"Show Bounding Box", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Camera Feed", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Key Points Visualization", None))
        self.show_skeleton_camera.setText(QCoreApplication.translate("MainWindow", u"Show in Skeleton", None))
        self.show_skeleton_white_frame.setText(QCoreApplication.translate("MainWindow", u"Show in Skeleton", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"ACTION:", None))
        self.add_action_button.setText(QCoreApplication.translate("MainWindow", u"Add Action", None))
        self.start_recording_button.setText(QCoreApplication.translate("MainWindow", u"START \n"
" RECORDING", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Preparation\n"
"Time", None))
        self.refresh_button.setText(QCoreApplication.translate("MainWindow", u"Refresh", None))
        self.start_recording_button_2.setText(QCoreApplication.translate("MainWindow", u"STOP \n"
" RECORDING", None))
        self.delete_action_button.setText(QCoreApplication.translate("MainWindow", u"Delete", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Dataset Details", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Folder Location", None))
        self.browseButton.setText(QCoreApplication.translate("MainWindow", u"Browse", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"CPU Usage", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"RAM Usage", None))
        self.cpu_label.setText(QCoreApplication.translate("MainWindow", u"--", None))
        self.ram_label.setText(QCoreApplication.translate("MainWindow", u"--", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"TIME:", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"GPU Usage", None))
        self.gpu_label.setText(QCoreApplication.translate("MainWindow", u"--", None))
        self.MainTab.setTabText(self.MainTab.indexOf(self.createDatasetTab), QCoreApplication.translate("MainWindow", u"Create Dataset", None))
        self.menuARMIS.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuView.setTitle(QCoreApplication.translate("MainWindow", u"View", None))
    # retranslateUi

