# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'FINAL-DESIGNeDaaiq.ui'
##
## Created by: Qt User Interface Compiler version 6.8.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QFrame,
    QGraphicsView, QGroupBox, QHeaderView, QLCDNumber,
    QLabel, QLineEdit, QMainWindow, QMenu,
    QMenuBar, QProgressBar, QPushButton, QSizePolicy,
    QSlider, QStatusBar, QTabWidget, QTableWidget,
    QTableWidgetItem, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1280, 714)
        font = QFont()
        font.setPointSize(11)
        MainWindow.setFont(font)
        self.fileNew = QAction(MainWindow)
        self.fileNew.setObjectName(u"fileNew")
        self.fileOpen = QAction(MainWindow)
        self.fileOpen.setObjectName(u"fileOpen")
        self.fileSave = QAction(MainWindow)
        self.fileSave.setObjectName(u"fileSave")
        self.fileExport = QAction(MainWindow)
        self.fileExport.setObjectName(u"fileExport")
        self.fileExit = QAction(MainWindow)
        self.fileExit.setObjectName(u"fileExit")
        self.actionviewCreateDataset = QAction(MainWindow)
        self.actionviewCreateDataset.setObjectName(u"actionviewCreateDataset")
        self.actionView_Home = QAction(MainWindow)
        self.actionView_Home.setObjectName(u"actionView_Home")
        self.actionView_Tutorial = QAction(MainWindow)
        self.actionView_Tutorial.setObjectName(u"actionView_Tutorial")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.MainTab = QTabWidget(self.centralwidget)
        self.MainTab.setObjectName(u"MainTab")
        self.MainTab.setEnabled(True)
        self.MainTab.setGeometry(QRect(10, 20, 1271, 651))
        font1 = QFont()
        font1.setFamilies([u"Segoe UI"])
        font1.setPointSize(18)
        self.MainTab.setFont(font1)
        self.MainTab.setAutoFillBackground(False)
        self.MainTab.setStyleSheet(u"border-color: rgb(0, 0, 0);")
        self.MainTab.setTabPosition(QTabWidget.TabPosition.North)
        self.MainTab.setTabShape(QTabWidget.TabShape.Rounded)
        self.MainTab.setIconSize(QSize(16, 16))
        self.MainTab.setElideMode(Qt.TextElideMode.ElideNone)
        self.importVideo = QWidget()
        self.importVideo.setObjectName(u"importVideo")
        self.groupBox_2 = QGroupBox(self.importVideo)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(1000, 10, 251, 581))
        font2 = QFont()
        font2.setPointSize(12)
        self.groupBox_2.setFont(font2)
        self.frame_7 = QFrame(self.groupBox_2)
        self.frame_7.setObjectName(u"frame_7")
        self.frame_7.setGeometry(QRect(10, 180, 231, 301))
        self.frame_7.setFrameShape(QFrame.Shape.Box)
        self.frame_7.setFrameShadow(QFrame.Shadow.Sunken)
        self.frame_7.setLineWidth(1)
        self.label_16 = QLabel(self.frame_7)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(0, 0, 231, 61))
        font3 = QFont()
        font3.setPointSize(16)
        font3.setBold(True)
        self.label_16.setFont(font3)
        self.label_16.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.behavior_change_freq_chkbox = QCheckBox(self.frame_7)
        self.behavior_change_freq_chkbox.setObjectName(u"behavior_change_freq_chkbox")
        self.behavior_change_freq_chkbox.setGeometry(QRect(10, 90, 221, 31))
        self.behavior_change_freq_chkbox.setFont(font2)
        self.tesk_taking_time_chkbox = QCheckBox(self.frame_7)
        self.tesk_taking_time_chkbox.setObjectName(u"tesk_taking_time_chkbox")
        self.tesk_taking_time_chkbox.setGeometry(QRect(10, 70, 211, 21))
        self.tesk_taking_time_chkbox.setFont(font2)
        self.behavior_count_freq_chkbox = QCheckBox(self.frame_7)
        self.behavior_count_freq_chkbox.setObjectName(u"behavior_count_freq_chkbox")
        self.behavior_count_freq_chkbox.setGeometry(QRect(10, 110, 211, 41))
        self.behavior_count_freq_chkbox.setFont(font2)
        self.label_20 = QLabel(self.frame_7)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(0, 140, 231, 61))
        self.label_20.setFont(font3)
        self.label_20.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.behavior_count_link_list_chkbox = QCheckBox(self.frame_7)
        self.behavior_count_link_list_chkbox.setObjectName(u"behavior_count_link_list_chkbox")
        self.behavior_count_link_list_chkbox.setGeometry(QRect(10, 200, 181, 51))
        self.behavior_count_link_list_chkbox.setFont(font2)
        self.event_timeline_chkbox = QCheckBox(self.frame_7)
        self.event_timeline_chkbox.setObjectName(u"event_timeline_chkbox")
        self.event_timeline_chkbox.setGeometry(QRect(10, 250, 131, 31))
        self.event_timeline_chkbox.setFont(font2)
        self.analyze_video_button = QPushButton(self.groupBox_2)
        self.analyze_video_button.setObjectName(u"analyze_video_button")
        self.analyze_video_button.setEnabled(False)
        self.analyze_video_button.setGeometry(QRect(10, 490, 231, 91))
        font4 = QFont()
        font4.setPointSize(20)
        font4.setBold(False)
        self.analyze_video_button.setFont(font4)
        self.recording_window_button = QPushButton(self.groupBox_2)
        self.recording_window_button.setObjectName(u"recording_window_button")
        self.recording_window_button.setGeometry(QRect(10, 30, 231, 61))
        self.recording_window_button.setFont(font4)
        self.play_pause_button_video_preview = QPushButton(self.groupBox_2)
        self.play_pause_button_video_preview.setObjectName(u"play_pause_button_video_preview")
        self.play_pause_button_video_preview.setEnabled(False)
        self.play_pause_button_video_preview.setGeometry(QRect(10, 100, 231, 71))
        font5 = QFont()
        font5.setPointSize(20)
        self.play_pause_button_video_preview.setFont(font5)
        self.video_preview_label_front = QLabel(self.importVideo)
        self.video_preview_label_front.setObjectName(u"video_preview_label_front")
        self.video_preview_label_front.setGeometry(QRect(10, 10, 491, 301))
        font6 = QFont()
        font6.setPointSize(16)
        font6.setItalic(True)
        self.video_preview_label_front.setFont(font6)
        self.video_preview_label_front.setFrameShape(QFrame.Shape.WinPanel)
        self.video_preview_label_front.setFrameShadow(QFrame.Shadow.Raised)
        self.video_preview_label_front.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.frame_5 = QFrame(self.importVideo)
        self.frame_5.setObjectName(u"frame_5")
        self.frame_5.setGeometry(QRect(10, 320, 981, 281))
        self.frame_5.setFrameShape(QFrame.Shape.WinPanel)
        self.frame_5.setFrameShadow(QFrame.Shadow.Raised)
        self.label_15 = QLabel(self.frame_5)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(10, 10, 211, 21))
        font7 = QFont()
        font7.setPointSize(12)
        font7.setItalic(True)
        self.label_15.setFont(font7)
        self.videoDirectory_center = QLineEdit(self.frame_5)
        self.videoDirectory_center.setObjectName(u"videoDirectory_center")
        self.videoDirectory_center.setGeometry(QRect(510, 40, 461, 31))
        self.videoDirectory_center.setFont(font7)
        self.videoDirectory_center.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.videoDirectory_center.setReadOnly(True)
        self.videoDirectory_center.setClearButtonEnabled(False)
        self.import_video_button_front = QPushButton(self.frame_5)
        self.import_video_button_front.setObjectName(u"import_video_button_front")
        self.import_video_button_front.setGeometry(QRect(290, 170, 181, 81))
        self.import_video_button_front.setFont(font4)
        self.import_video_button_front.setAutoFillBackground(False)
        self.importProgressBar_front = QProgressBar(self.frame_5)
        self.importProgressBar_front.setObjectName(u"importProgressBar_front")
        self.importProgressBar_front.setGeometry(QRect(10, 110, 461, 41))
        self.importProgressBar_front.setFont(font2)
        self.importProgressBar_front.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.importProgressBar_front.setAutoFillBackground(False)
        self.importProgressBar_front.setValue(0)
        self.importProgressBar_front.setAlignment(Qt.AlignmentFlag.AlignBottom|Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing)
        self.importProgressBar_front.setInvertedAppearance(False)
        self.status_label_front = QLabel(self.frame_5)
        self.status_label_front.setObjectName(u"status_label_front")
        self.status_label_front.setGeometry(QRect(10, 130, 461, 21))
        font8 = QFont()
        font8.setPointSize(11)
        font8.setItalic(True)
        self.status_label_front.setFont(font8)
        self.status_label_front.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.videoDirectory_front = QLineEdit(self.frame_5)
        self.videoDirectory_front.setObjectName(u"videoDirectory_front")
        self.videoDirectory_front.setGeometry(QRect(10, 40, 461, 31))
        self.videoDirectory_front.setFont(font7)
        self.videoDirectory_front.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.videoDirectory_front.setReadOnly(True)
        self.videoDirectory_front.setClearButtonEnabled(False)
        self.importProgressBar_center = QProgressBar(self.frame_5)
        self.importProgressBar_center.setObjectName(u"importProgressBar_center")
        self.importProgressBar_center.setGeometry(QRect(510, 110, 461, 41))
        self.importProgressBar_center.setFont(font2)
        self.importProgressBar_center.setAutoFillBackground(False)
        self.importProgressBar_center.setValue(0)
        self.importProgressBar_center.setAlignment(Qt.AlignmentFlag.AlignBottom|Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing)
        self.importProgressBar_center.setInvertedAppearance(False)
        self.label_17 = QLabel(self.frame_5)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(510, 10, 191, 21))
        self.label_17.setFont(font7)
        self.import_video_button_center = QPushButton(self.frame_5)
        self.import_video_button_center.setObjectName(u"import_video_button_center")
        self.import_video_button_center.setGeometry(QRect(800, 170, 171, 81))
        self.import_video_button_center.setFont(font4)
        self.import_video_button_center.setAutoFillBackground(False)
        self.status_label_center = QLabel(self.frame_5)
        self.status_label_center.setObjectName(u"status_label_center")
        self.status_label_center.setGeometry(QRect(510, 130, 461, 21))
        self.status_label_center.setFont(font8)
        self.status_label_center.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.somelabelforprogrss = QLabel(self.frame_5)
        self.somelabelforprogrss.setObjectName(u"somelabelforprogrss")
        self.somelabelforprogrss.setGeometry(QRect(10, 80, 451, 31))
        font9 = QFont()
        font9.setPointSize(12)
        font9.setBold(False)
        font9.setItalic(True)
        self.somelabelforprogrss.setFont(font9)
        self.somelabelforprogrss.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.somelabelforprogrss_2 = QLabel(self.frame_5)
        self.somelabelforprogrss_2.setObjectName(u"somelabelforprogrss_2")
        self.somelabelforprogrss_2.setGeometry(QRect(510, 80, 461, 31))
        self.somelabelforprogrss_2.setFont(font9)
        self.somelabelforprogrss_2.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.somelabelforprogrss_3 = QLabel(self.frame_5)
        self.somelabelforprogrss_3.setObjectName(u"somelabelforprogrss_3")
        self.somelabelforprogrss_3.setGeometry(QRect(10, 170, 181, 31))
        self.somelabelforprogrss_3.setFont(font9)
        self.somelabelforprogrss_3.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.somelabelforprogrss_7 = QLabel(self.frame_5)
        self.somelabelforprogrss_7.setObjectName(u"somelabelforprogrss_7")
        self.somelabelforprogrss_7.setGeometry(QRect(510, 160, 191, 31))
        self.somelabelforprogrss_7.setFont(font9)
        self.somelabelforprogrss_7.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.somelabelforprogrss_4 = QLabel(self.frame_5)
        self.somelabelforprogrss_4.setObjectName(u"somelabelforprogrss_4")
        self.somelabelforprogrss_4.setGeometry(QRect(10, 200, 161, 31))
        self.somelabelforprogrss_4.setFont(font9)
        self.somelabelforprogrss_4.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.somelabelforprogrss_5 = QLabel(self.frame_5)
        self.somelabelforprogrss_5.setObjectName(u"somelabelforprogrss_5")
        self.somelabelforprogrss_5.setGeometry(QRect(510, 190, 161, 31))
        self.somelabelforprogrss_5.setFont(font9)
        self.somelabelforprogrss_5.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.front_frame_count = QLabel(self.frame_5)
        self.front_frame_count.setObjectName(u"front_frame_count")
        self.front_frame_count.setGeometry(QRect(200, 170, 81, 31))
        font10 = QFont()
        font10.setPointSize(12)
        font10.setBold(True)
        font10.setItalic(False)
        self.front_frame_count.setFont(font10)
        self.front_frame_count.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.front_video_length = QLabel(self.frame_5)
        self.front_video_length.setObjectName(u"front_video_length")
        self.front_video_length.setGeometry(QRect(200, 200, 81, 31))
        self.front_video_length.setFont(font10)
        self.front_video_length.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.center_frame_count = QLabel(self.frame_5)
        self.center_frame_count.setObjectName(u"center_frame_count")
        self.center_frame_count.setGeometry(QRect(720, 160, 71, 31))
        self.center_frame_count.setFont(font10)
        self.center_frame_count.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.center_video_length = QLabel(self.frame_5)
        self.center_video_length.setObjectName(u"center_video_length")
        self.center_video_length.setGeometry(QRect(720, 190, 71, 31))
        self.center_video_length.setFont(font10)
        self.center_video_length.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.label_29 = QLabel(self.importVideo)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(510, 10, 191, 21))
        self.label_29.setFont(font2)
        self.label_29.setAutoFillBackground(True)
        self.label_29.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_30 = QLabel(self.importVideo)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(10, 10, 191, 21))
        self.label_30.setFont(font2)
        self.label_30.setAutoFillBackground(True)
        self.label_30.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.video_preview_label_center = QLabel(self.importVideo)
        self.video_preview_label_center.setObjectName(u"video_preview_label_center")
        self.video_preview_label_center.setGeometry(QRect(500, 10, 491, 301))
        self.video_preview_label_center.setFont(font6)
        self.video_preview_label_center.setFrameShape(QFrame.Shape.WinPanel)
        self.video_preview_label_center.setFrameShadow(QFrame.Shadow.Raised)
        self.video_preview_label_center.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.MainTab.addTab(self.importVideo, "")
        self.video_preview_label_center.raise_()
        self.video_preview_label_front.raise_()
        self.frame_5.raise_()
        self.label_29.raise_()
        self.label_30.raise_()
        self.groupBox_2.raise_()
        self.analyticsTab = QWidget()
        self.analyticsTab.setObjectName(u"analyticsTab")
        self.pushButton = QPushButton(self.analyticsTab)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(550, 10, 141, 31))
        self.pushButton.setFont(font2)
        self.center_video_preview_label = QLabel(self.analyticsTab)
        self.center_video_preview_label.setObjectName(u"center_video_preview_label")
        self.center_video_preview_label.setGeometry(QRect(710, 50, 551, 191))
        font11 = QFont()
        font11.setPointSize(18)
        font11.setItalic(True)
        self.center_video_preview_label.setFont(font11)
        self.center_video_preview_label.setFrameShape(QFrame.Shape.Panel)
        self.center_video_preview_label.setFrameShadow(QFrame.Shadow.Raised)
        self.center_video_preview_label.setLineWidth(2)
        self.center_video_preview_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_14 = QLabel(self.analyticsTab)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(20, 0, 291, 51))
        self.label_14.setFont(font1)
        self.label_14.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.label_40 = QLabel(self.analyticsTab)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(710, 10, 551, 41))
        self.label_40.setFont(font1)
        self.label_40.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.comboBox = QComboBox(self.analyticsTab)
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(280, 10, 261, 31))
        font12 = QFont()
        font12.setPointSize(14)
        self.comboBox.setFont(font12)
        self.front_video_preview_label = QLabel(self.analyticsTab)
        self.front_video_preview_label.setObjectName(u"front_video_preview_label")
        self.front_video_preview_label.setGeometry(QRect(710, 250, 551, 291))
        self.front_video_preview_label.setFont(font11)
        self.front_video_preview_label.setFrameShape(QFrame.Shape.Panel)
        self.front_video_preview_label.setFrameShadow(QFrame.Shadow.Raised)
        self.front_video_preview_label.setLineWidth(2)
        self.front_video_preview_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_13 = QLabel(self.analyticsTab)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(710, 50, 191, 31))
        self.label_13.setFont(font7)
        self.label_13.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_19 = QLabel(self.analyticsTab)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(710, 250, 181, 31))
        self.label_19.setFont(font7)
        self.label_19.setAutoFillBackground(True)
        self.label_19.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.graphicsView_events_timeline = QGraphicsView(self.analyticsTab)
        self.graphicsView_events_timeline.setObjectName(u"graphicsView_events_timeline")
        self.graphicsView_events_timeline.setGeometry(QRect(20, 450, 681, 151))
        self.graphicsView_events_timeline.setFrameShape(QFrame.Shape.WinPanel)
        self.graphicsView_events_timeline.setFrameShadow(QFrame.Shadow.Raised)
        brush = QBrush(QColor(0, 0, 0, 255))
        brush.setStyle(Qt.NoBrush)
        self.graphicsView_events_timeline.setBackgroundBrush(brush)
        self.play_pause_button_analytics = QPushButton(self.analyticsTab)
        self.play_pause_button_analytics.setObjectName(u"play_pause_button_analytics")
        self.play_pause_button_analytics.setEnabled(False)
        self.play_pause_button_analytics.setGeometry(QRect(720, 550, 261, 51))
        font13 = QFont()
        font13.setPointSize(22)
        self.play_pause_button_analytics.setFont(font13)
        self.see_full_data_button = QPushButton(self.analyticsTab)
        self.see_full_data_button.setObjectName(u"see_full_data_button")
        self.see_full_data_button.setGeometry(QRect(1000, 550, 261, 51))
        self.see_full_data_button.setFont(font13)
        self.heatmap_present_label = QLabel(self.analyticsTab)
        self.heatmap_present_label.setObjectName(u"heatmap_present_label")
        self.heatmap_present_label.setGeometry(QRect(20, 50, 681, 341))
        self.heatmap_present_label.setFont(font6)
        self.heatmap_present_label.setFrameShape(QFrame.Shape.WinPanel)
        self.heatmap_present_label.setFrameShadow(QFrame.Shadow.Raised)
        self.heatmap_present_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.timeFrameContainer = QWidget(self.analyticsTab)
        self.timeFrameContainer.setObjectName(u"timeFrameContainer")
        self.timeFrameContainer.setGeometry(QRect(20, 390, 681, 51))
        self.originalVideoOnlyChkBox_center_analytics = QCheckBox(self.analyticsTab)
        self.originalVideoOnlyChkBox_center_analytics.setObjectName(u"originalVideoOnlyChkBox_center_analytics")
        self.originalVideoOnlyChkBox_center_analytics.setGeometry(QRect(900, 50, 131, 31))
        self.originalVideoOnlyChkBox_center_analytics.setAutoFillBackground(False)
        self.originalVideoOnlyChkBox_center_analytics.setChecked(False)
        self.originalVideoOnlyChkBox_front_analytics = QCheckBox(self.analyticsTab)
        self.originalVideoOnlyChkBox_front_analytics.setObjectName(u"originalVideoOnlyChkBox_front_analytics")
        self.originalVideoOnlyChkBox_front_analytics.setGeometry(QRect(890, 250, 131, 31))
        self.originalVideoOnlyChkBox_front_analytics.setAutoFillBackground(False)
        self.originalVideoOnlyChkBox_front_analytics.setChecked(False)
        self.keypointsOnlyChkBox_Center_analytics = QCheckBox(self.analyticsTab)
        self.keypointsOnlyChkBox_Center_analytics.setObjectName(u"keypointsOnlyChkBox_Center_analytics")
        self.keypointsOnlyChkBox_Center_analytics.setGeometry(QRect(1030, 49, 141, 31))
        self.keypointsOnlyChkBox_Center_analytics.setAutoFillBackground(False)
        self.keypointsOnlyChkBox_front_analytics = QCheckBox(self.analyticsTab)
        self.keypointsOnlyChkBox_front_analytics.setObjectName(u"keypointsOnlyChkBox_front_analytics")
        self.keypointsOnlyChkBox_front_analytics.setGeometry(QRect(1030, 250, 141, 31))
        self.keypointsOnlyChkBox_front_analytics.setAutoFillBackground(False)
        self.MainTab.addTab(self.analyticsTab, "")
        self.pushButton.raise_()
        self.center_video_preview_label.raise_()
        self.label_14.raise_()
        self.label_40.raise_()
        self.comboBox.raise_()
        self.front_video_preview_label.raise_()
        self.label_13.raise_()
        self.graphicsView_events_timeline.raise_()
        self.play_pause_button_analytics.raise_()
        self.see_full_data_button.raise_()
        self.heatmap_present_label.raise_()
        self.label_19.raise_()
        self.timeFrameContainer.raise_()
        self.originalVideoOnlyChkBox_center_analytics.raise_()
        self.originalVideoOnlyChkBox_front_analytics.raise_()
        self.keypointsOnlyChkBox_Center_analytics.raise_()
        self.keypointsOnlyChkBox_front_analytics.raise_()
        self.createDatasetTab = QWidget()
        self.createDatasetTab.setObjectName(u"createDatasetTab")
        self.cameraComboBox = QComboBox(self.createDatasetTab)
        self.cameraComboBox.setObjectName(u"cameraComboBox")
        self.cameraComboBox.setGeometry(QRect(80, 20, 211, 31))
        font14 = QFont()
        font14.setFamilies([u"Segoe UI"])
        font14.setPointSize(14)
        self.cameraComboBox.setFont(font14)
        self.cameraComboBox.setEditable(True)
        self.label_Camera = QLabel(self.createDatasetTab)
        self.label_Camera.setObjectName(u"label_Camera")
        self.label_Camera.setGeometry(QRect(10, 20, 71, 31))
        self.label_Camera.setFont(font14)
        self.openCamera = QPushButton(self.createDatasetTab)
        self.openCamera.setObjectName(u"openCamera")
        self.openCamera.setGeometry(QRect(300, 20, 131, 31))
        font15 = QFont()
        font15.setFamilies([u"Segoe UI"])
        font15.setPointSize(12)
        self.openCamera.setFont(font15)
        self.closeCamera = QPushButton(self.createDatasetTab)
        self.closeCamera.setObjectName(u"closeCamera")
        self.closeCamera.setGeometry(QRect(440, 20, 131, 31))
        self.closeCamera.setFont(font15)
        self.frame = QFrame(self.createDatasetTab)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(10, 70, 961, 521))
        self.frame.setFrameShape(QFrame.Shape.Box)
        self.frame.setFrameShadow(QFrame.Shadow.Sunken)
        self.frame.setLineWidth(2)
        self.camera_feed = QLabel(self.frame)
        self.camera_feed.setObjectName(u"camera_feed")
        self.camera_feed.setGeometry(QRect(10, 10, 461, 271))
        font16 = QFont()
        font16.setFamilies([u"Segoe UI"])
        font16.setPointSize(16)
        font16.setBold(False)
        font16.setItalic(True)
        self.camera_feed.setFont(font16)
        self.camera_feed.setFrameShape(QFrame.Shape.WinPanel)
        self.camera_feed.setFrameShadow(QFrame.Shadow.Raised)
        self.camera_feed.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.white_frame_feed = QLabel(self.frame)
        self.white_frame_feed.setObjectName(u"white_frame_feed")
        self.white_frame_feed.setGeometry(QRect(490, 10, 461, 271))
        self.white_frame_feed.setFont(font16)
        self.white_frame_feed.setFrameShape(QFrame.Shape.WinPanel)
        self.white_frame_feed.setFrameShadow(QFrame.Shadow.Raised)
        self.white_frame_feed.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.darkMode_whiteframe = QCheckBox(self.frame)
        self.darkMode_whiteframe.setObjectName(u"darkMode_whiteframe")
        self.darkMode_whiteframe.setGeometry(QRect(500, 310, 141, 31))
        self.darkMode_whiteframe.setFont(font14)
        self.darkMode_whiteframe.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.show_whiteframe_boundingbox = QCheckBox(self.frame)
        self.show_whiteframe_boundingbox.setObjectName(u"show_whiteframe_boundingbox")
        self.show_whiteframe_boundingbox.setGeometry(QRect(500, 340, 221, 31))
        self.show_whiteframe_boundingbox.setFont(font14)
        self.show_whiteframe_boundingbox.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.showCameraLandmarksChkBox = QCheckBox(self.frame)
        self.showCameraLandmarksChkBox.setObjectName(u"showCameraLandmarksChkBox")
        self.showCameraLandmarksChkBox.setGeometry(QRect(20, 310, 221, 31))
        self.showCameraLandmarksChkBox.setFont(font14)
        self.showCameraLandmarksChkBox.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.showCameraBoundingBoxChkBox = QCheckBox(self.frame)
        self.showCameraBoundingBoxChkBox.setObjectName(u"showCameraBoundingBoxChkBox")
        self.showCameraBoundingBoxChkBox.setGeometry(QRect(20, 340, 191, 31))
        self.showCameraBoundingBoxChkBox.setFont(font14)
        self.showCameraBoundingBoxChkBox.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.label = QLabel(self.frame)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 280, 461, 31))
        font17 = QFont()
        font17.setFamilies([u"Segoe UI"])
        font17.setPointSize(16)
        self.label.setFont(font17)
        self.label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_2 = QLabel(self.frame)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(490, 280, 461, 31))
        self.label_2.setFont(font17)
        self.label_2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.show_skeleton_camera = QCheckBox(self.frame)
        self.show_skeleton_camera.setObjectName(u"show_skeleton_camera")
        self.show_skeleton_camera.setGeometry(QRect(280, 310, 171, 31))
        self.show_skeleton_camera.setFont(font14)
        self.show_skeleton_camera.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.show_skeleton_white_frame = QCheckBox(self.frame)
        self.show_skeleton_white_frame.setObjectName(u"show_skeleton_white_frame")
        self.show_skeleton_white_frame.setGeometry(QRect(760, 310, 171, 31))
        self.show_skeleton_white_frame.setFont(font14)
        self.show_skeleton_white_frame.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.frame_2 = QFrame(self.frame)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(10, 380, 941, 111))
        self.frame_2.setFrameShape(QFrame.Shape.Box)
        self.frame_2.setFrameShadow(QFrame.Shadow.Sunken)
        self.frame_2.setLineWidth(2)
        self.label_4 = QLabel(self.frame_2)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(20, 20, 91, 31))
        self.label_4.setFont(font17)
        self.label_4.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.action_comboBox = QComboBox(self.frame_2)
        self.action_comboBox.setObjectName(u"action_comboBox")
        self.action_comboBox.setGeometry(QRect(120, 20, 271, 31))
        self.action_comboBox.setFont(font14)
        self.action_comboBox.setEditable(True)
        self.add_action_button = QPushButton(self.frame_2)
        self.add_action_button.setObjectName(u"add_action_button")
        self.add_action_button.setGeometry(QRect(120, 60, 121, 31))
        self.add_action_button.setFont(font14)
        self.recording_button = QPushButton(self.frame_2)
        self.recording_button.setObjectName(u"recording_button")
        self.recording_button.setGeometry(QRect(550, 20, 171, 71))
        palette = QPalette()
        brush1 = QBrush(QColor(0, 0, 0, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        brush2 = QBrush(QColor(170, 255, 127, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush2)
        brush3 = QBrush(QColor(170, 255, 255, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Light, brush3)
        palette.setBrush(QPalette.Active, QPalette.Text, brush1)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush1)
        palette.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette.setBrush(QPalette.Active, QPalette.Window, brush2)
        brush4 = QBrush(QColor(0, 0, 0, 128))
        brush4.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush4)
#endif
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        brush5 = QBrush(QColor(255, 255, 255, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Light, brush5)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush2)
        brush6 = QBrush(QColor(0, 0, 0, 128))
        brush6.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush6)
#endif
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Light, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush1)
        brush7 = QBrush(QColor(255, 255, 255, 135))
        brush7.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush7)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        brush8 = QBrush(QColor(0, 0, 0, 128))
        brush8.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush8)
#endif
        self.recording_button.setPalette(palette)
        font18 = QFont()
        font18.setFamilies([u"Segoe UI"])
        font18.setPointSize(18)
        font18.setBold(True)
        self.recording_button.setFont(font18)
        self.recording_button.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.recording_button.setStyleSheet(u"background-color: rgb(170, 255, 127);\n"
"border-radius: 15px; /* Adjust the radius as needed */\n"
"color: black; /* Set the text color */\n"
"border: 1px solid black; /* Optional: Add a border */")
        self.refresh_button = QPushButton(self.frame_2)
        self.refresh_button.setObjectName(u"refresh_button")
        self.refresh_button.setGeometry(QRect(400, 20, 111, 31))
        self.refresh_button.setFont(font14)
        self.delete_action_button = QPushButton(self.frame_2)
        self.delete_action_button.setObjectName(u"delete_action_button")
        self.delete_action_button.setGeometry(QRect(270, 60, 121, 31))
        self.delete_action_button.setFont(font14)
        self.status_label = QLabel(self.frame)
        self.status_label.setObjectName(u"status_label")
        self.status_label.setGeometry(QRect(70, 20, 131, 21))
        palette1 = QPalette()
        brush9 = QBrush(QColor(0, 255, 0, 255))
        brush9.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush9)
        palette1.setBrush(QPalette.Active, QPalette.Text, brush9)
        palette1.setBrush(QPalette.Active, QPalette.ButtonText, brush9)
        brush10 = QBrush(QColor(0, 255, 0, 128))
        brush10.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Active, QPalette.PlaceholderText, brush10)
#endif
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush9)
        palette1.setBrush(QPalette.Inactive, QPalette.Text, brush9)
        palette1.setBrush(QPalette.Inactive, QPalette.ButtonText, brush9)
        brush11 = QBrush(QColor(0, 255, 0, 128))
        brush11.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush11)
#endif
        palette1.setBrush(QPalette.Disabled, QPalette.WindowText, brush9)
        palette1.setBrush(QPalette.Disabled, QPalette.Text, brush9)
        palette1.setBrush(QPalette.Disabled, QPalette.ButtonText, brush9)
        brush12 = QBrush(QColor(0, 255, 0, 128))
        brush12.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush12)
#endif
        self.status_label.setPalette(palette1)
        font19 = QFont()
        font19.setFamilies([u"Segoe UI"])
        font19.setPointSize(12)
        font19.setBold(True)
        self.status_label.setFont(font19)
        self.status_label.setStyleSheet(u"color: rgb(0, 255, 0);")
        self.status_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.label_12 = QLabel(self.frame)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(20, 20, 51, 21))
        self.label_12.setFont(font15)
        self.label_12.setAutoFillBackground(True)
        self.line_5 = QFrame(self.frame)
        self.line_5.setObjectName(u"line_5")
        self.line_5.setGeometry(QRect(10, 490, 941, 21))
        self.line_5.setFrameShape(QFrame.Shape.HLine)
        self.line_5.setFrameShadow(QFrame.Shadow.Sunken)
        self.groupBox = QGroupBox(self.createDatasetTab)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(980, 50, 281, 541))
        font20 = QFont()
        font20.setFamilies([u"Segoe UI"])
        font20.setPointSize(16)
        font20.setBold(True)
        self.groupBox.setFont(font20)
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setStyleSheet(u"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:2 rgba(255, 255, 255, 255));")
        self.groupBox.setFlat(False)
        self.label_3 = QLabel(self.groupBox)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 40, 121, 21))
        self.label_3.setFont(font15)
        self.directoryLineEdit = QLineEdit(self.groupBox)
        self.directoryLineEdit.setObjectName(u"directoryLineEdit")
        self.directoryLineEdit.setGeometry(QRect(20, 70, 241, 31))
        font21 = QFont()
        font21.setFamilies([u"Segoe UI"])
        font21.setPointSize(10)
        font21.setItalic(True)
        self.directoryLineEdit.setFont(font21)
        self.browseButton = QPushButton(self.groupBox)
        self.browseButton.setObjectName(u"browseButton")
        self.browseButton.setGeometry(QRect(90, 110, 91, 31))
        font22 = QFont()
        font22.setFamilies([u"Segoe UI"])
        font22.setPointSize(11)
        self.browseButton.setFont(font22)
        self.refresh_action_list = QPushButton(self.groupBox)
        self.refresh_action_list.setObjectName(u"refresh_action_list")
        self.refresh_action_list.setGeometry(QRect(90, 310, 91, 31))
        self.refresh_action_list.setFont(font)
        self.action_table = QTableWidget(self.groupBox)
        if (self.action_table.columnCount() < 2):
            self.action_table.setColumnCount(2)
        if (self.action_table.rowCount() < 7):
            self.action_table.setRowCount(7)
        self.action_table.setObjectName(u"action_table")
        self.action_table.setGeometry(QRect(10, 150, 261, 151))
        self.action_table.setFrameShape(QFrame.Shape.WinPanel)
        self.action_table.setFrameShadow(QFrame.Shadow.Raised)
        self.action_table.setLineWidth(2)
        self.action_table.setAutoScrollMargin(9)
        self.action_table.setProperty(u"showDropIndicator", False)
        self.action_table.setDragEnabled(False)
        self.action_table.setDragDropOverwriteMode(False)
        self.action_table.setShowGrid(True)
        self.action_table.setGridStyle(Qt.PenStyle.SolidLine)
        self.action_table.setSortingEnabled(False)
        self.action_table.setWordWrap(True)
        self.action_table.setCornerButtonEnabled(False)
        self.action_table.setRowCount(7)
        self.action_table.setColumnCount(2)
        self.action_table.horizontalHeader().setCascadingSectionResizes(False)
        self.action_table.horizontalHeader().setMinimumSectionSize(37)
        self.action_table.horizontalHeader().setDefaultSectionSize(111)
        self.action_table.horizontalHeader().setProperty(u"showSortIndicator", False)
        self.action_table.verticalHeader().setVisible(False)
        self.action_table.verticalHeader().setDefaultSectionSize(25)
        self.interval_slider = QSlider(self.groupBox)
        self.interval_slider.setObjectName(u"interval_slider")
        self.interval_slider.setGeometry(QRect(10, 370, 211, 21))
        self.interval_slider.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.interval_slider.setMinimum(1)
        self.interval_slider.setMaximum(10)
        self.interval_slider.setSliderPosition(3)
        self.interval_slider.setOrientation(Qt.Orientation.Horizontal)
        self.interval_slider.setTickPosition(QSlider.TickPosition.TicksAbove)
        self.interval_label = QLabel(self.groupBox)
        self.interval_label.setObjectName(u"interval_label")
        self.interval_label.setGeometry(QRect(230, 360, 41, 41))
        self.interval_label.setFont(font18)
        self.interval_label.setStyleSheet(u"border-color: rgb(0, 0, 0);\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.interval_label.setFrameShape(QFrame.Shape.Box)
        self.interval_label.setFrameShadow(QFrame.Shadow.Sunken)
        self.interval_label.setLineWidth(1)
        self.interval_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.interval_label.setMargin(0)
        self.label_8 = QLabel(self.groupBox)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 350, 151, 21))
        font23 = QFont()
        font23.setFamilies([u"Segoe UI"])
        font23.setPointSize(12)
        font23.setBold(False)
        self.label_8.setFont(font23)
        self.label_8.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.sequence_label = QLabel(self.groupBox)
        self.sequence_label.setObjectName(u"sequence_label")
        self.sequence_label.setGeometry(QRect(230, 430, 41, 41))
        self.sequence_label.setFont(font18)
        self.sequence_label.setStyleSheet(u"border-color: rgb(0, 0, 0);\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.sequence_label.setFrameShape(QFrame.Shape.Box)
        self.sequence_label.setFrameShadow(QFrame.Shadow.Sunken)
        self.sequence_label.setLineWidth(1)
        self.sequence_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.sequence_label.setMargin(0)
        self.sequence_slider = QSlider(self.groupBox)
        self.sequence_slider.setObjectName(u"sequence_slider")
        self.sequence_slider.setGeometry(QRect(10, 440, 211, 21))
        self.sequence_slider.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.sequence_slider.setMinimum(1)
        self.sequence_slider.setMaximum(60)
        self.sequence_slider.setValue(30)
        self.sequence_slider.setSliderPosition(30)
        self.sequence_slider.setOrientation(Qt.Orientation.Horizontal)
        self.sequence_slider.setTickPosition(QSlider.TickPosition.TicksAbove)
        self.label_11 = QLabel(self.groupBox)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(10, 410, 171, 21))
        self.label_11.setFont(font2)
        self.label_11.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.label_5 = QLabel(self.createDatasetTab)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(790, 10, 81, 16))
        font24 = QFont()
        font24.setFamilies([u"Segoe UI"])
        font24.setPointSize(10)
        self.label_5.setFont(font24)
        self.cpu_label = QLabel(self.createDatasetTab)
        self.cpu_label.setObjectName(u"cpu_label")
        self.cpu_label.setGeometry(QRect(790, 20, 91, 41))
        palette2 = QPalette()
        brush13 = QBrush(QColor(0, 85, 255, 255))
        brush13.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.WindowText, brush13)
        palette2.setBrush(QPalette.Inactive, QPalette.WindowText, brush13)
        brush14 = QBrush(QColor(120, 120, 120, 255))
        brush14.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Disabled, QPalette.WindowText, brush14)
        self.cpu_label.setPalette(palette2)
        font25 = QFont()
        font25.setFamilies([u"Segoe UI"])
        font25.setPointSize(20)
        font25.setBold(True)
        self.cpu_label.setFont(font25)
        self.ram_label = QLabel(self.createDatasetTab)
        self.ram_label.setObjectName(u"ram_label")
        self.ram_label.setGeometry(QRect(930, 20, 91, 41))
        palette3 = QPalette()
        brush15 = QBrush(QColor(170, 0, 0, 255))
        brush15.setStyle(Qt.SolidPattern)
        palette3.setBrush(QPalette.Active, QPalette.WindowText, brush15)
        palette3.setBrush(QPalette.Inactive, QPalette.WindowText, brush15)
        palette3.setBrush(QPalette.Disabled, QPalette.WindowText, brush14)
        self.ram_label.setPalette(palette3)
        self.ram_label.setFont(font25)
        self.label_9 = QLabel(self.createDatasetTab)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(1060, 10, 81, 16))
        self.label_9.setFont(font24)
        self.gpu_label = QLabel(self.createDatasetTab)
        self.gpu_label.setObjectName(u"gpu_label")
        self.gpu_label.setGeometry(QRect(1060, 20, 91, 41))
        palette4 = QPalette()
        brush16 = QBrush(QColor(85, 170, 0, 255))
        brush16.setStyle(Qt.SolidPattern)
        palette4.setBrush(QPalette.Active, QPalette.WindowText, brush16)
        palette4.setBrush(QPalette.Inactive, QPalette.WindowText, brush16)
        palette4.setBrush(QPalette.Disabled, QPalette.WindowText, brush14)
        self.gpu_label.setPalette(palette4)
        self.gpu_label.setFont(font25)
        self.label_10 = QLabel(self.createDatasetTab)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(670, 10, 51, 21))
        self.label_10.setFont(font24)
        self.fps_label = QLabel(self.createDatasetTab)
        self.fps_label.setObjectName(u"fps_label")
        self.fps_label.setGeometry(QRect(670, 20, 91, 41))
        palette5 = QPalette()
        brush17 = QBrush(QColor(170, 85, 255, 255))
        brush17.setStyle(Qt.SolidPattern)
        palette5.setBrush(QPalette.Active, QPalette.WindowText, brush17)
        palette5.setBrush(QPalette.Inactive, QPalette.WindowText, brush17)
        palette5.setBrush(QPalette.Disabled, QPalette.WindowText, brush14)
        self.fps_label.setPalette(palette5)
        self.fps_label.setFont(font25)
        self.label_6 = QLabel(self.createDatasetTab)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(930, 10, 81, 16))
        self.label_6.setFont(font24)
        self.MainTab.addTab(self.createDatasetTab, "")
        self.timeLCD = QLCDNumber(self.centralwidget)
        self.timeLCD.setObjectName(u"timeLCD")
        self.timeLCD.setGeometry(QRect(1090, 10, 161, 41))
        font26 = QFont()
        font26.setPointSize(10)
        self.timeLCD.setFont(font26)
        self.timeLCD.setAutoFillBackground(True)
        self.timeLCD.setFrameShadow(QFrame.Shadow.Sunken)
        self.timeLCD.setLineWidth(1)
        self.timeLCD.setMidLineWidth(0)
        self.timeLCD.setDigitCount(8)
        self.timeLCD.setSegmentStyle(QLCDNumber.SegmentStyle.Filled)
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(1050, 10, 31, 21))
        self.label_7.setFont(font24)
        self.date_label = QLabel(self.centralwidget)
        self.date_label.setObjectName(u"date_label")
        self.date_label.setGeometry(QRect(800, 10, 61, 20))
        self.date_label.setFont(font24)
        self.day_label = QLabel(self.centralwidget)
        self.day_label.setObjectName(u"day_label")
        self.day_label.setGeometry(QRect(860, 10, 211, 41))
        font27 = QFont()
        font27.setFamilies([u"Segoe UI"])
        font27.setPointSize(18)
        font27.setItalic(False)
        self.day_label.setFont(font27)
        self.line = QFrame(self.centralwidget)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(10, -40, 1251, 91))
        self.line.setLineWidth(2)
        self.line.setFrameShape(QFrame.Shape.HLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_2 = QFrame(self.centralwidget)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(463, 10, 51, 51))
        self.line_2.setFrameShadow(QFrame.Shadow.Raised)
        self.line_2.setLineWidth(1)
        self.line_2.setFrameShape(QFrame.Shape.VLine)
        self.line_3 = QFrame(self.centralwidget)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(1240, 10, 41, 51))
        self.line_3.setFrameShadow(QFrame.Shadow.Raised)
        self.line_3.setLineWidth(1)
        self.line_3.setFrameShape(QFrame.Shape.VLine)
        self.date_label_2 = QLabel(self.centralwidget)
        self.date_label_2.setObjectName(u"date_label_2")
        self.date_label_2.setGeometry(QRect(510, 10, 91, 20))
        self.date_label_2.setFont(font24)
        MainWindow.setCentralWidget(self.centralwidget)
        self.line.raise_()
        self.MainTab.raise_()
        self.timeLCD.raise_()
        self.label_7.raise_()
        self.date_label.raise_()
        self.day_label.raise_()
        self.line_2.raise_()
        self.line_3.raise_()
        self.date_label_2.raise_()
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1280, 26))
        self.menuARMIS = QMenu(self.menubar)
        self.menuARMIS.setObjectName(u"menuARMIS")
        self.menuARMIS.setStyleSheet(u"border-color: rgb(0, 0, 0);")
        self.menuARMIS.setTearOffEnabled(False)
        self.menuARMIS.setSeparatorsCollapsible(False)
        self.menuView = QMenu(self.menubar)
        self.menuView.setObjectName(u"menuView")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuARMIS.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menuARMIS.addAction(self.fileNew)
        self.menuARMIS.addAction(self.fileOpen)
        self.menuARMIS.addAction(self.fileSave)
        self.menuARMIS.addAction(self.fileExport)
        self.menuARMIS.addAction(self.fileExit)
        self.menuView.addAction(self.actionView_Home)
        self.menuView.addAction(self.actionView_Tutorial)
        self.menuView.addAction(self.actionviewCreateDataset)

        self.retranslateUi(MainWindow)

        self.MainTab.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Pose Estimation Analytics", None))
        self.fileNew.setText(QCoreApplication.translate("MainWindow", u"New", None))
        self.fileOpen.setText(QCoreApplication.translate("MainWindow", u"Open", None))
        self.fileSave.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.fileExport.setText(QCoreApplication.translate("MainWindow", u"Export", None))
        self.fileExit.setText(QCoreApplication.translate("MainWindow", u"Exit", None))
        self.actionviewCreateDataset.setText(QCoreApplication.translate("MainWindow", u"View Create Dataset Tab", None))
        self.actionView_Home.setText(QCoreApplication.translate("MainWindow", u"View Home", None))
        self.actionView_Tutorial.setText(QCoreApplication.translate("MainWindow", u"View Tutorial", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"Analytics Options", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"Classroom\n"
"Heatmap View", None))
        self.behavior_change_freq_chkbox.setText(QCoreApplication.translate("MainWindow", u"Behavior Change Frequency", None))
        self.tesk_taking_time_chkbox.setText(QCoreApplication.translate("MainWindow", u"Test-Taking Time Duration", None))
        self.behavior_count_freq_chkbox.setText(QCoreApplication.translate("MainWindow", u"Behavior Count Frequency", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"Other\n"
"Visualizations", None))
        self.behavior_count_link_list_chkbox.setText(QCoreApplication.translate("MainWindow", u"Behavior Count\n"
"Frequency [Linked List]", None))
        self.event_timeline_chkbox.setText(QCoreApplication.translate("MainWindow", u"Event Timeline", None))
        self.analyze_video_button.setText(QCoreApplication.translate("MainWindow", u"Analyze\n"
"Footages", None))
        self.recording_window_button.setText(QCoreApplication.translate("MainWindow", u"Record Session", None))
        self.play_pause_button_video_preview.setText(QCoreApplication.translate("MainWindow", u"PLAY PREVIEW", None))
        self.video_preview_label_front.setText(QCoreApplication.translate("MainWindow", u"Import a video to see preview", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Front Video File Location:", None))
        self.videoDirectory_center.setText(QCoreApplication.translate("MainWindow", u"Import a video file to be analyzed.", None))
        self.videoDirectory_center.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Find a video file", None))
        self.import_video_button_front.setText(QCoreApplication.translate("MainWindow", u"Browse", None))
        self.status_label_front.setText(QCoreApplication.translate("MainWindow", u"[ IMPORT A VIDEO ]", None))
        self.videoDirectory_front.setText(QCoreApplication.translate("MainWindow", u"Import a video file to be analyzed.", None))
        self.videoDirectory_front.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Find a video file", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"Center Video File Location:", None))
        self.import_video_button_center.setText(QCoreApplication.translate("MainWindow", u"Browse", None))
        self.status_label_center.setText(QCoreApplication.translate("MainWindow", u"[ IMPORT A VIDEO ]", None))
        self.somelabelforprogrss.setText(QCoreApplication.translate("MainWindow", u"Front Video Progress Bar", None))
        self.somelabelforprogrss_2.setText(QCoreApplication.translate("MainWindow", u"Center Video Progress Bar", None))
        self.somelabelforprogrss_3.setText(QCoreApplication.translate("MainWindow", u"Front Video Frame Count:", None))
        self.somelabelforprogrss_7.setText(QCoreApplication.translate("MainWindow", u"Center Video Frame Count:", None))
        self.somelabelforprogrss_4.setText(QCoreApplication.translate("MainWindow", u"Front Video Length:", None))
        self.somelabelforprogrss_5.setText(QCoreApplication.translate("MainWindow", u"Center Video Length:", None))
        self.front_frame_count.setText(QCoreApplication.translate("MainWindow", u"--", None))
        self.front_video_length.setText(QCoreApplication.translate("MainWindow", u"--", None))
        self.center_frame_count.setText(QCoreApplication.translate("MainWindow", u"--", None))
        self.center_video_length.setText(QCoreApplication.translate("MainWindow", u"--", None))
        self.label_29.setText(QCoreApplication.translate("MainWindow", u"Video Preview [CENTER]", None))
        self.label_30.setText(QCoreApplication.translate("MainWindow", u"Video Preview [FRONT]", None))
        self.video_preview_label_center.setText(QCoreApplication.translate("MainWindow", u"Import a video to see preview", None))
        self.MainTab.setTabText(self.MainTab.indexOf(self.importVideo), QCoreApplication.translate("MainWindow", u"Import Video", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"Refresh Heatmap", None))
        self.center_video_preview_label.setText(QCoreApplication.translate("MainWindow", u"Import an Examination Footage First", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"CLASSROOM HEATMAP", None))
        self.label_40.setText(QCoreApplication.translate("MainWindow", u"EXAMINATION FOOTAGE PLAYBACK", None))
        self.comboBox.setCurrentText("")
        self.front_video_preview_label.setText(QCoreApplication.translate("MainWindow", u"Import an Examination Footage First", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Center Video Placement", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"Front Video Placement", None))
        self.play_pause_button_analytics.setText(QCoreApplication.translate("MainWindow", u"PAUSE", None))
        self.see_full_data_button.setText(QCoreApplication.translate("MainWindow", u"SEE FULL DATA", None))
        self.heatmap_present_label.setText(QCoreApplication.translate("MainWindow", u"Heatmap Visualization will be presented here.", None))
        self.originalVideoOnlyChkBox_center_analytics.setText(QCoreApplication.translate("MainWindow", u"Original Video Only", None))
        self.originalVideoOnlyChkBox_front_analytics.setText(QCoreApplication.translate("MainWindow", u"Original Video Only", None))
        self.keypointsOnlyChkBox_Center_analytics.setText(QCoreApplication.translate("MainWindow", u"Keypoints Only", None))
        self.keypointsOnlyChkBox_front_analytics.setText(QCoreApplication.translate("MainWindow", u"Keypoints Only", None))
        self.MainTab.setTabText(self.MainTab.indexOf(self.analyticsTab), QCoreApplication.translate("MainWindow", u"Analytics", None))
        self.label_Camera.setText(QCoreApplication.translate("MainWindow", u"Camera", None))
        self.openCamera.setText(QCoreApplication.translate("MainWindow", u"Open Camera", None))
        self.closeCamera.setText(QCoreApplication.translate("MainWindow", u"Close Camera", None))
        self.camera_feed.setText(QCoreApplication.translate("MainWindow", u"Camera Feed will show here", None))
        self.white_frame_feed.setText(QCoreApplication.translate("MainWindow", u"Body Pose Key Points will show here", None))
        self.darkMode_whiteframe.setText(QCoreApplication.translate("MainWindow", u"Dark Mode", None))
        self.show_whiteframe_boundingbox.setText(QCoreApplication.translate("MainWindow", u"Show Bounding Boxes", None))
        self.showCameraLandmarksChkBox.setText(QCoreApplication.translate("MainWindow", u"Show Body Landmarks", None))
        self.showCameraBoundingBoxChkBox.setText(QCoreApplication.translate("MainWindow", u"Show Bounding Box", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Camera Feed", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Key Points Visualization", None))
        self.show_skeleton_camera.setText(QCoreApplication.translate("MainWindow", u"Show in Skeleton", None))
        self.show_skeleton_white_frame.setText(QCoreApplication.translate("MainWindow", u"Show in Skeleton", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"ACTION:", None))
        self.add_action_button.setText(QCoreApplication.translate("MainWindow", u"Add Action", None))
        self.recording_button.setText(QCoreApplication.translate("MainWindow", u"START\n"
"RECORDING", None))
        self.refresh_button.setText(QCoreApplication.translate("MainWindow", u"Refresh", None))
        self.delete_action_button.setText(QCoreApplication.translate("MainWindow", u"Delete", None))
        self.status_label.setText(QCoreApplication.translate("MainWindow", u"NOT RECORDING", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Status:", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Dataset Details", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Folder Location", None))
        self.browseButton.setText(QCoreApplication.translate("MainWindow", u"Browse", None))
        self.refresh_action_list.setText(QCoreApplication.translate("MainWindow", u"Refresh", None))
        self.interval_label.setText(QCoreApplication.translate("MainWindow", u"--", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Break Interval Length", None))
        self.sequence_label.setText(QCoreApplication.translate("MainWindow", u"--", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"No. of Frames per Video", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"CPU Usage", None))
        self.cpu_label.setText(QCoreApplication.translate("MainWindow", u"--", None))
        self.ram_label.setText(QCoreApplication.translate("MainWindow", u"--", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"GPU Usage", None))
        self.gpu_label.setText(QCoreApplication.translate("MainWindow", u"--", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"FPS:", None))
        self.fps_label.setText(QCoreApplication.translate("MainWindow", u"--", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"RAM Usage", None))
        self.MainTab.setTabText(self.MainTab.indexOf(self.createDatasetTab), QCoreApplication.translate("MainWindow", u"Create Dataset", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Time:", None))
        self.date_label.setText(QCoreApplication.translate("MainWindow", u"Today is:", None))
        self.day_label.setText(QCoreApplication.translate("MainWindow", u"--", None))
        self.date_label_2.setText(QCoreApplication.translate("MainWindow", u"Session Name:", None))
        self.menuARMIS.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuView.setTitle(QCoreApplication.translate("MainWindow", u"View", None))
    # retranslateUi

