from PySide2.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PySide2.QtWidgets import *

from utils import CameraFeed

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1203, 754)
        self.actionExit = QAction(MainWindow)
        self.actionExit.setObjectName(u"actionExit")
        self.actionOpen = QAction(MainWindow)
        self.actionOpen.setObjectName(u"actionOpen")
        self.actionSave = QAction(MainWindow)
        self.actionSave.setObjectName(u"actionSave")
        self.actionExport = QAction(MainWindow)
        self.actionExport.setObjectName(u"actionExport")
        self.actionExit_2 = QAction(MainWindow)
        self.actionExit_2.setObjectName(u"actionExit_2")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.MainTab = QTabWidget(self.centralwidget)
        self.MainTab.setObjectName(u"MainTab")
        self.MainTab.setGeometry(QRect(0, 0, 1200, 720))
        font = QFont()
        font.setFamily(u"Segoe UI")
        font.setPointSize(18)
        self.MainTab.setFont(font)
        self.analyticstTab = QWidget()
        self.analyticstTab.setObjectName(u"analyticstTab")
        self.MainTab.addTab(self.analyticstTab, "")
        self.createDatasetTab = QWidget()
        self.createDatasetTab.setObjectName(u"createDatasetTab")
        self.cameraComboBox = QComboBox(self.createDatasetTab)
        self.cameraComboBox.setObjectName(u"cameraComboBox")
        self.cameraComboBox.setGeometry(QRect(80, 10, 191, 31))
        font1 = QFont()
        font1.setPointSize(14)
        self.cameraComboBox.setFont(font1)
        self.label_Camera = QLabel(self.createDatasetTab)
        self.label_Camera.setObjectName(u"label_Camera")
        self.label_Camera.setGeometry(QRect(10, 10, 71, 31))
        self.label_Camera.setFont(font1)
        self.openCamera = QPushButton(self.createDatasetTab)
        self.openCamera.setObjectName(u"openCamera")
        self.openCamera.setGeometry(QRect(280, 10, 131, 31))
        font2 = QFont()
        font2.setPointSize(12)
        self.openCamera.setFont(font2)
        self.closeCamera = QPushButton(self.createDatasetTab)
        self.closeCamera.setObjectName(u"closeCamera")
        self.closeCamera.setGeometry(QRect(420, 10, 131, 31))
        self.closeCamera.setFont(font2)
        self.frame = QFrame(self.createDatasetTab)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(10, 50, 901, 621))
        self.frame.setFrameShape(QFrame.Box)
        self.frame.setFrameShadow(QFrame.Sunken)
        self.frame.setLineWidth(2)
        self.camera_feed = QLabel(self.frame)
        self.camera_feed.setObjectName(u"camera_feed")
        self.camera_feed.setGeometry(QRect(10, 10, 431, 300))
        font3 = QFont()
        font3.setPointSize(16)
        font3.setBold(False)
        font3.setItalic(True)
        font3.setWeight(50)
        self.camera_feed.setFont(font3)
        self.camera_feed.setFrameShape(QFrame.Box)
        self.camera_feed.setFrameShadow(QFrame.Sunken)
        self.camera_feed.setAlignment(Qt.AlignCenter)
        self.white_frame_feed = QLabel(self.frame)
        self.white_frame_feed.setObjectName(u"white_frame_feed")
        self.white_frame_feed.setGeometry(QRect(460, 10, 431, 300))
        self.white_frame_feed.setFont(font3)
        self.white_frame_feed.setFrameShape(QFrame.Box)
        self.white_frame_feed.setFrameShadow(QFrame.Sunken)
        self.white_frame_feed.setAlignment(Qt.AlignCenter)
        self.darkMode_whiteframe = QCheckBox(self.frame)
        self.darkMode_whiteframe.setObjectName(u"darkMode_whiteframe")
        self.darkMode_whiteframe.setGeometry(QRect(460, 340, 141, 31))
        self.darkMode_whiteframe.setFont(font1)
        self.show_whiteframe_boundingbox = QCheckBox(self.frame)
        self.show_whiteframe_boundingbox.setObjectName(u"show_whiteframe_boundingbox")
        self.show_whiteframe_boundingbox.setGeometry(QRect(460, 370, 221, 31))
        self.show_whiteframe_boundingbox.setFont(font1)
        self.showCameraLandmarksChkBox = QCheckBox(self.frame)
        self.showCameraLandmarksChkBox.setObjectName(u"showCameraLandmarksChkBox")
        self.showCameraLandmarksChkBox.setGeometry(QRect(10, 340, 221, 31))
        self.showCameraLandmarksChkBox.setFont(font1)
        self.showCameraBoundingBoxChkBox = QCheckBox(self.frame)
        self.showCameraBoundingBoxChkBox.setObjectName(u"showCameraBoundingBoxChkBox")
        self.showCameraBoundingBoxChkBox.setGeometry(QRect(10, 370, 191, 31))
        self.showCameraBoundingBoxChkBox.setFont(font1)
        self.label = QLabel(self.frame)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(120, 310, 211, 31))
        font4 = QFont()
        font4.setPointSize(16)
        self.label.setFont(font4)
        self.label.setAlignment(Qt.AlignCenter)
        self.label_2 = QLabel(self.frame)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(560, 310, 231, 31))
        self.label_2.setFont(font4)
        self.label_2.setAlignment(Qt.AlignCenter)
        self.show_skeleton_camera = QCheckBox(self.frame)
        self.show_skeleton_camera.setObjectName(u"show_skeleton_camera")
        self.show_skeleton_camera.setGeometry(QRect(260, 340, 171, 31))
        self.show_skeleton_camera.setFont(font1)
        self.show_skeleton_white_frame = QCheckBox(self.frame)
        self.show_skeleton_white_frame.setObjectName(u"show_skeleton_white_frame")
        self.show_skeleton_white_frame.setGeometry(QRect(710, 340, 171, 31))
        self.show_skeleton_white_frame.setFont(font1)
        self.groupBox = QGroupBox(self.createDatasetTab)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(930, 40, 261, 631))
        font5 = QFont()
        font5.setFamily(u"Segoe UI")
        font5.setPointSize(16)
        font5.setBold(True)
        font5.setWeight(75)
        self.groupBox.setFont(font5)
        self.groupBox.setStyleSheet(u"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:2 rgba(255, 255, 255, 255));")
        self.groupBox.setFlat(False)
        self.label_3 = QLabel(self.groupBox)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 40, 121, 21))
        font6 = QFont()
        font6.setFamily(u"Segoe UI")
        font6.setPointSize(12)
        self.label_3.setFont(font6)
        self.lineEdit = QLineEdit(self.groupBox)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(20, 70, 221, 31))
        font7 = QFont()
        font7.setFamily(u"Segoe UI")
        font7.setPointSize(12)
        font7.setItalic(True)
        self.lineEdit.setFont(font7)
        self.pushButton = QPushButton(self.groupBox)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(90, 110, 75, 23))
        font8 = QFont()
        font8.setFamily(u"Segoe UI")
        font8.setPointSize(10)
        self.pushButton.setFont(font8)
        self.tableView = QTableView(self.groupBox)
        self.tableView.setObjectName(u"tableView")
        self.tableView.setGeometry(QRect(10, 150, 241, 192))
        self.MainTab.addTab(self.createDatasetTab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1203, 21))
        self.menuARMIS = QMenu(self.menubar)
        self.menuARMIS.setObjectName(u"menuARMIS")
        self.menuView = QMenu(self.menubar)
        self.menuView.setObjectName(u"menuView")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuARMIS.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menuARMIS.addAction(self.actionExit)
        self.menuARMIS.addAction(self.actionOpen)
        self.menuARMIS.addAction(self.actionSave)
        self.menuARMIS.addAction(self.actionExport)
        self.menuARMIS.addAction(self.actionExit_2)

        self.retranslateUi(MainWindow)

        self.MainTab.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionExit.setText(QCoreApplication.translate("MainWindow", u"New", None))
        self.actionOpen.setText(QCoreApplication.translate("MainWindow", u"Open", None))
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.actionExport.setText(QCoreApplication.translate("MainWindow", u"Export", None))
        self.actionExit_2.setText(QCoreApplication.translate("MainWindow", u"Exit", None))
        self.MainTab.setTabText(self.MainTab.indexOf(self.analyticstTab), QCoreApplication.translate("MainWindow", u"Analytics", None))
        self.label_Camera.setText(QCoreApplication.translate("MainWindow", u"Camera", None))
        self.openCamera.setText(QCoreApplication.translate("MainWindow", u"Open Camera", None))
        self.closeCamera.setText(QCoreApplication.translate("MainWindow", u"Close Camera", None))
        self.camera_feed.setText(QCoreApplication.translate("MainWindow", u"Camera Feed will show here", None))
        self.white_frame_feed.setText(QCoreApplication.translate("MainWindow", u"Body Pose Key Points will show here", None))
        self.darkMode_whiteframe.setText(QCoreApplication.translate("MainWindow", u"Dark Mode", None))
        self.show_whiteframe_boundingbox.setText(QCoreApplication.translate("MainWindow", u"Show Bounding Boxes", None))
        self.showCameraLandmarksChkBox.setText(QCoreApplication.translate("MainWindow", u"Show Body Landmarks", None))
        self.showCameraBoundingBoxChkBox.setText(QCoreApplication.translate("MainWindow", u"Show Bounding Box", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Camera Feed", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Key Points Visualization", None))
        self.show_skeleton_camera.setText(QCoreApplication.translate("MainWindow", u"Show in Skeleton", None))
        self.show_skeleton_white_frame.setText(QCoreApplication.translate("MainWindow", u"Show in Skeleton", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Data Details", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Dataset Location", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"Browse", None))
        self.MainTab.setTabText(self.MainTab.indexOf(self.createDatasetTab), QCoreApplication.translate("MainWindow", u"Create Dataset", None))
        self.menuARMIS.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuView.setTitle(QCoreApplication.translate("MainWindow", u"View", None))
    # retranslateUi

