# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Design 1eEgJQL.ui'
##
## Created by: Qt User Interface Compiler version 5.14.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1204, 721)
        self.actionExit = QAction(MainWindow)
        self.actionExit.setObjectName(u"actionExit")
        self.actionOpen = QAction(MainWindow)
        self.actionOpen.setObjectName(u"actionOpen")
        self.actionSave = QAction(MainWindow)
        self.actionSave.setObjectName(u"actionSave")
        self.actionExport = QAction(MainWindow)
        self.actionExport.setObjectName(u"actionExport")
        self.actionExit_2 = QAction(MainWindow)
        self.actionExit_2.setObjectName(u"actionExit_2")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.MainTab = QTabWidget(self.centralwidget)
        self.MainTab.setObjectName(u"MainTab")
        self.MainTab.setGeometry(QRect(0, 0, 1200, 691))
        font = QFont()
        font.setFamily(u"Segoe UI")
        font.setPointSize(18)
        self.MainTab.setFont(font)
        self.MainTab.setTabPosition(QTabWidget.North)
        self.MainTab.setTabShape(QTabWidget.Rounded)
        self.MainTab.setIconSize(QSize(16, 16))
        self.MainTab.setElideMode(Qt.ElideNone)
        self.analyticstTab = QWidget()
        self.analyticstTab.setObjectName(u"analyticstTab")
        self.MainTab.addTab(self.analyticstTab, "")
        self.createDatasetTab = QWidget()
        self.createDatasetTab.setObjectName(u"createDatasetTab")
        self.cameraComboBox = QComboBox(self.createDatasetTab)
        self.cameraComboBox.setObjectName(u"cameraComboBox")
        self.cameraComboBox.setGeometry(QRect(80, 20, 211, 31))
        font1 = QFont()
        font1.setPointSize(14)
        self.cameraComboBox.setFont(font1)
        self.cameraComboBox.setEditable(True)
        self.label_Camera = QLabel(self.createDatasetTab)
        self.label_Camera.setObjectName(u"label_Camera")
        self.label_Camera.setGeometry(QRect(10, 20, 71, 31))
        self.label_Camera.setFont(font1)
        self.openCamera = QPushButton(self.createDatasetTab)
        self.openCamera.setObjectName(u"openCamera")
        self.openCamera.setGeometry(QRect(300, 20, 131, 31))
        font2 = QFont()
        font2.setPointSize(12)
        self.openCamera.setFont(font2)
        self.closeCamera = QPushButton(self.createDatasetTab)
        self.closeCamera.setObjectName(u"closeCamera")
        self.closeCamera.setGeometry(QRect(440, 20, 131, 31))
        self.closeCamera.setFont(font2)
        self.frame = QFrame(self.createDatasetTab)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(10, 70, 901, 571))
        self.frame.setFrameShape(QFrame.Box)
        self.frame.setFrameShadow(QFrame.Sunken)
        self.frame.setLineWidth(2)
        self.camera_feed = QLabel(self.frame)
        self.camera_feed.setObjectName(u"camera_feed")
        self.camera_feed.setGeometry(QRect(10, 10, 431, 242))
        font3 = QFont()
        font3.setPointSize(16)
        font3.setBold(False)
        font3.setItalic(True)
        font3.setWeight(50)
        self.camera_feed.setFont(font3)
        self.camera_feed.setFrameShape(QFrame.Box)
        self.camera_feed.setFrameShadow(QFrame.Sunken)
        self.camera_feed.setAlignment(Qt.AlignCenter)
        self.white_frame_feed = QLabel(self.frame)
        self.white_frame_feed.setObjectName(u"white_frame_feed")
        self.white_frame_feed.setGeometry(QRect(460, 10, 431, 242))
        self.white_frame_feed.setFont(font3)
        self.white_frame_feed.setFrameShape(QFrame.Box)
        self.white_frame_feed.setFrameShadow(QFrame.Sunken)
        self.white_frame_feed.setAlignment(Qt.AlignCenter)
        self.darkMode_whiteframe = QCheckBox(self.frame)
        self.darkMode_whiteframe.setObjectName(u"darkMode_whiteframe")
        self.darkMode_whiteframe.setGeometry(QRect(460, 280, 141, 31))
        self.darkMode_whiteframe.setFont(font1)
        self.darkMode_whiteframe.setCursor(QCursor(Qt.PointingHandCursor))
        self.show_whiteframe_boundingbox = QCheckBox(self.frame)
        self.show_whiteframe_boundingbox.setObjectName(u"show_whiteframe_boundingbox")
        self.show_whiteframe_boundingbox.setGeometry(QRect(460, 310, 221, 31))
        self.show_whiteframe_boundingbox.setFont(font1)
        self.show_whiteframe_boundingbox.setCursor(QCursor(Qt.PointingHandCursor))
        self.showCameraLandmarksChkBox = QCheckBox(self.frame)
        self.showCameraLandmarksChkBox.setObjectName(u"showCameraLandmarksChkBox")
        self.showCameraLandmarksChkBox.setGeometry(QRect(10, 280, 221, 31))
        self.showCameraLandmarksChkBox.setFont(font1)
        self.showCameraLandmarksChkBox.setCursor(QCursor(Qt.PointingHandCursor))
        self.showCameraBoundingBoxChkBox = QCheckBox(self.frame)
        self.showCameraBoundingBoxChkBox.setObjectName(u"showCameraBoundingBoxChkBox")
        self.showCameraBoundingBoxChkBox.setGeometry(QRect(10, 310, 191, 31))
        self.showCameraBoundingBoxChkBox.setFont(font1)
        self.showCameraBoundingBoxChkBox.setCursor(QCursor(Qt.PointingHandCursor))
        self.label = QLabel(self.frame)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(120, 250, 211, 31))
        font4 = QFont()
        font4.setPointSize(16)
        self.label.setFont(font4)
        self.label.setAlignment(Qt.AlignCenter)
        self.label_2 = QLabel(self.frame)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(560, 250, 231, 31))
        self.label_2.setFont(font4)
        self.label_2.setAlignment(Qt.AlignCenter)
        self.show_skeleton_camera = QCheckBox(self.frame)
        self.show_skeleton_camera.setObjectName(u"show_skeleton_camera")
        self.show_skeleton_camera.setGeometry(QRect(270, 280, 171, 31))
        self.show_skeleton_camera.setFont(font1)
        self.show_skeleton_camera.setCursor(QCursor(Qt.PointingHandCursor))
        self.show_skeleton_white_frame = QCheckBox(self.frame)
        self.show_skeleton_white_frame.setObjectName(u"show_skeleton_white_frame")
        self.show_skeleton_white_frame.setGeometry(QRect(720, 280, 171, 31))
        self.show_skeleton_white_frame.setFont(font1)
        self.show_skeleton_white_frame.setCursor(QCursor(Qt.PointingHandCursor))
        self.frame_2 = QFrame(self.frame)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(10, 350, 881, 211))
        self.frame_2.setFrameShape(QFrame.Box)
        self.frame_2.setFrameShadow(QFrame.Sunken)
        self.frame_2.setLineWidth(2)
        self.label_4 = QLabel(self.frame_2)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(20, 20, 91, 31))
        self.label_4.setFont(font4)
        self.label_4.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.action_comboBox = QComboBox(self.frame_2)
        self.action_comboBox.setObjectName(u"action_comboBox")
        self.action_comboBox.setGeometry(QRect(140, 20, 231, 31))
        self.action_comboBox.setFont(font1)
        self.action_comboBox.setEditable(True)
        self.add_action_button = QPushButton(self.frame_2)
        self.add_action_button.setObjectName(u"add_action_button")
        self.add_action_button.setGeometry(QRect(140, 60, 111, 31))
        self.add_action_button.setFont(font1)
        self.recording_button = QPushButton(self.frame_2)
        self.recording_button.setObjectName(u"recording_button")
        self.recording_button.setGeometry(QRect(590, 70, 191, 111))
        palette = QPalette()
        brush = QBrush(QColor(0, 0, 0, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(170, 255, 127, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        brush2 = QBrush(QColor(170, 255, 255, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette.setBrush(QPalette.Active, QPalette.Window, brush1)
        brush3 = QBrush(QColor(0, 0, 0, 128))
        brush3.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush3)
#endif
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        brush4 = QBrush(QColor(255, 255, 255, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Light, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        brush5 = QBrush(QColor(0, 0, 0, 128))
        brush5.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush5)
#endif
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Light, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        brush6 = QBrush(QColor(0, 0, 0, 128))
        brush6.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush6)
#endif
        self.recording_button.setPalette(palette)
        font5 = QFont()
        font5.setFamily(u"Segoe UI")
        font5.setPointSize(20)
        font5.setBold(True)
        font5.setWeight(75)
        self.recording_button.setFont(font5)
        self.recording_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.recording_button.setStyleSheet(u"background-color: rgb(170, 255, 127);\n"
"border-radius: 15px; /* Adjust the radius as needed */\n"
"color: black; /* Set the text color */\n"
"border: 1px solid black; /* Optional: Add a border */")
        self.interval_slider = QSlider(self.frame_2)
        self.interval_slider.setObjectName(u"interval_slider")
        self.interval_slider.setGeometry(QRect(180, 110, 311, 31))
        self.interval_slider.setCursor(QCursor(Qt.PointingHandCursor))
        self.interval_slider.setMinimum(1)
        self.interval_slider.setMaximum(10)
        self.interval_slider.setSliderPosition(3)
        self.interval_slider.setOrientation(Qt.Horizontal)
        self.interval_slider.setTickPosition(QSlider.TicksAbove)
        self.label_8 = QLabel(self.frame_2)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(20, 110, 121, 31))
        self.label_8.setFont(font4)
        self.label_8.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.refresh_button = QPushButton(self.frame_2)
        self.refresh_button.setObjectName(u"refresh_button")
        self.refresh_button.setGeometry(QRect(380, 20, 111, 31))
        self.refresh_button.setFont(font1)
        self.delete_action_button = QPushButton(self.frame_2)
        self.delete_action_button.setObjectName(u"delete_action_button")
        self.delete_action_button.setGeometry(QRect(260, 60, 111, 31))
        self.delete_action_button.setFont(font1)
        self.label_11 = QLabel(self.frame_2)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(20, 160, 141, 31))
        self.label_11.setFont(font4)
        self.label_11.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.sequence_slider = QSlider(self.frame_2)
        self.sequence_slider.setObjectName(u"sequence_slider")
        self.sequence_slider.setGeometry(QRect(180, 160, 311, 31))
        self.sequence_slider.setCursor(QCursor(Qt.PointingHandCursor))
        self.sequence_slider.setMinimum(1)
        self.sequence_slider.setMaximum(60)
        self.sequence_slider.setValue(30)
        self.sequence_slider.setSliderPosition(30)
        self.sequence_slider.setOrientation(Qt.Horizontal)
        self.sequence_slider.setTickPosition(QSlider.TicksAbove)
        self.label_12 = QLabel(self.frame_2)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(550, 20, 71, 31))
        self.status_label = QLabel(self.frame_2)
        self.status_label.setObjectName(u"status_label")
        self.status_label.setGeometry(QRect(630, 20, 201, 31))
        palette1 = QPalette()
        brush7 = QBrush(QColor(0, 255, 0, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush7)
        palette1.setBrush(QPalette.Active, QPalette.Text, brush7)
        palette1.setBrush(QPalette.Active, QPalette.ButtonText, brush7)
        brush8 = QBrush(QColor(0, 255, 0, 128))
        brush8.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Active, QPalette.PlaceholderText, brush8)
#endif
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush7)
        palette1.setBrush(QPalette.Inactive, QPalette.Text, brush7)
        palette1.setBrush(QPalette.Inactive, QPalette.ButtonText, brush7)
        brush9 = QBrush(QColor(0, 255, 0, 128))
        brush9.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush9)
#endif
        palette1.setBrush(QPalette.Disabled, QPalette.WindowText, brush7)
        palette1.setBrush(QPalette.Disabled, QPalette.Text, brush7)
        palette1.setBrush(QPalette.Disabled, QPalette.ButtonText, brush7)
        brush10 = QBrush(QColor(0, 255, 0, 128))
        brush10.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush10)
#endif
        self.status_label.setPalette(palette1)
        font6 = QFont()
        font6.setFamily(u"Segoe UI")
        font6.setPointSize(18)
        font6.setBold(True)
        font6.setWeight(75)
        self.status_label.setFont(font6)
        self.status_label.setStyleSheet(u"color: rgb(0, 255, 0);")
        self.status_label.setAlignment(Qt.AlignCenter)
        self.groupBox = QGroupBox(self.createDatasetTab)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(920, 60, 261, 581))
        font7 = QFont()
        font7.setFamily(u"Segoe UI")
        font7.setPointSize(16)
        font7.setBold(True)
        font7.setWeight(75)
        self.groupBox.setFont(font7)
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setStyleSheet(u"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:2 rgba(255, 255, 255, 255));")
        self.groupBox.setFlat(False)
        self.label_3 = QLabel(self.groupBox)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 40, 121, 21))
        font8 = QFont()
        font8.setFamily(u"Segoe UI")
        font8.setPointSize(12)
        self.label_3.setFont(font8)
        self.directoryLineEdit = QLineEdit(self.groupBox)
        self.directoryLineEdit.setObjectName(u"directoryLineEdit")
        self.directoryLineEdit.setGeometry(QRect(20, 70, 221, 31))
        font9 = QFont()
        font9.setFamily(u"Segoe UI")
        font9.setPointSize(10)
        font9.setItalic(True)
        self.directoryLineEdit.setFont(font9)
        self.browseButton = QPushButton(self.groupBox)
        self.browseButton.setObjectName(u"browseButton")
        self.browseButton.setGeometry(QRect(90, 110, 91, 31))
        font10 = QFont()
        font10.setFamily(u"Segoe UI")
        font10.setPointSize(11)
        self.browseButton.setFont(font10)
        self.refresh_action_list = QPushButton(self.groupBox)
        self.refresh_action_list.setObjectName(u"refresh_action_list")
        self.refresh_action_list.setGeometry(QRect(90, 360, 91, 31))
        font11 = QFont()
        font11.setPointSize(11)
        self.refresh_action_list.setFont(font11)
        self.action_table = QTableWidget(self.groupBox)
        self.action_table.setObjectName(u"action_table")
        self.action_table.setGeometry(QRect(10, 160, 241, 192))
        self.label_5 = QLabel(self.createDatasetTab)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(680, 10, 81, 16))
        font12 = QFont()
        font12.setPointSize(10)
        self.label_5.setFont(font12)
        self.label_6 = QLabel(self.createDatasetTab)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(780, 10, 81, 16))
        self.label_6.setFont(font12)
        self.cpu_label = QLabel(self.createDatasetTab)
        self.cpu_label.setObjectName(u"cpu_label")
        self.cpu_label.setGeometry(QRect(680, 20, 91, 41))
        palette2 = QPalette()
        brush11 = QBrush(QColor(0, 85, 255, 255))
        brush11.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.WindowText, brush11)
        palette2.setBrush(QPalette.Inactive, QPalette.WindowText, brush11)
        brush12 = QBrush(QColor(120, 120, 120, 255))
        brush12.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Disabled, QPalette.WindowText, brush12)
        self.cpu_label.setPalette(palette2)
        font13 = QFont()
        font13.setPointSize(20)
        font13.setBold(True)
        font13.setWeight(75)
        self.cpu_label.setFont(font13)
        self.ram_label = QLabel(self.createDatasetTab)
        self.ram_label.setObjectName(u"ram_label")
        self.ram_label.setGeometry(QRect(780, 20, 91, 41))
        palette3 = QPalette()
        brush13 = QBrush(QColor(170, 0, 0, 255))
        brush13.setStyle(Qt.SolidPattern)
        palette3.setBrush(QPalette.Active, QPalette.WindowText, brush13)
        palette3.setBrush(QPalette.Inactive, QPalette.WindowText, brush13)
        palette3.setBrush(QPalette.Disabled, QPalette.WindowText, brush12)
        self.ram_label.setPalette(palette3)
        self.ram_label.setFont(font13)
        self.timeLCD = QLCDNumber(self.createDatasetTab)
        self.timeLCD.setObjectName(u"timeLCD")
        self.timeLCD.setGeometry(QRect(1030, 10, 151, 51))
        self.timeLCD.setLineWidth(1)
        self.timeLCD.setMidLineWidth(0)
        self.timeLCD.setDigitCount(8)
        self.timeLCD.setSegmentStyle(QLCDNumber.Filled)
        self.label_7 = QLabel(self.createDatasetTab)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(990, 10, 41, 21))
        self.label_7.setFont(font12)
        self.label_9 = QLabel(self.createDatasetTab)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(880, 10, 81, 16))
        self.label_9.setFont(font12)
        self.gpu_label = QLabel(self.createDatasetTab)
        self.gpu_label.setObjectName(u"gpu_label")
        self.gpu_label.setGeometry(QRect(880, 20, 91, 41))
        palette4 = QPalette()
        brush14 = QBrush(QColor(85, 170, 0, 255))
        brush14.setStyle(Qt.SolidPattern)
        palette4.setBrush(QPalette.Active, QPalette.WindowText, brush14)
        palette4.setBrush(QPalette.Inactive, QPalette.WindowText, brush14)
        palette4.setBrush(QPalette.Disabled, QPalette.WindowText, brush12)
        self.gpu_label.setPalette(palette4)
        self.gpu_label.setFont(font13)
        self.label_10 = QLabel(self.createDatasetTab)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(590, 10, 51, 21))
        self.label_10.setFont(font12)
        self.fps_label = QLabel(self.createDatasetTab)
        self.fps_label.setObjectName(u"fps_label")
        self.fps_label.setGeometry(QRect(590, 20, 91, 41))
        palette5 = QPalette()
        brush15 = QBrush(QColor(170, 85, 255, 255))
        brush15.setStyle(Qt.SolidPattern)
        palette5.setBrush(QPalette.Active, QPalette.WindowText, brush15)
        palette5.setBrush(QPalette.Inactive, QPalette.WindowText, brush15)
        palette5.setBrush(QPalette.Disabled, QPalette.WindowText, brush12)
        self.fps_label.setPalette(palette5)
        self.fps_label.setFont(font13)
        self.MainTab.addTab(self.createDatasetTab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1204, 21))
        self.menuARMIS = QMenu(self.menubar)
        self.menuARMIS.setObjectName(u"menuARMIS")
        self.menuView = QMenu(self.menubar)
        self.menuView.setObjectName(u"menuView")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuARMIS.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menuARMIS.addAction(self.actionExit)
        self.menuARMIS.addAction(self.actionOpen)
        self.menuARMIS.addAction(self.actionSave)
        self.menuARMIS.addAction(self.actionExport)
        self.menuARMIS.addAction(self.actionExit_2)

        self.retranslateUi(MainWindow)

        self.MainTab.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Pose Estimation Analytics", None))
        self.actionExit.setText(QCoreApplication.translate("MainWindow", u"New", None))
        self.actionOpen.setText(QCoreApplication.translate("MainWindow", u"Open", None))
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.actionExport.setText(QCoreApplication.translate("MainWindow", u"Export", None))
        self.actionExit_2.setText(QCoreApplication.translate("MainWindow", u"Exit", None))
        self.MainTab.setTabText(self.MainTab.indexOf(self.analyticstTab), QCoreApplication.translate("MainWindow", u"Analytics", None))
        self.label_Camera.setText(QCoreApplication.translate("MainWindow", u"Camera", None))
        self.openCamera.setText(QCoreApplication.translate("MainWindow", u"Open Camera", None))
        self.closeCamera.setText(QCoreApplication.translate("MainWindow", u"Close Camera", None))
        self.camera_feed.setText(QCoreApplication.translate("MainWindow", u"Camera Feed will show here", None))
        self.white_frame_feed.setText(QCoreApplication.translate("MainWindow", u"Body Pose Key Points will show here", None))
        self.darkMode_whiteframe.setText(QCoreApplication.translate("MainWindow", u"Dark Mode", None))
        self.show_whiteframe_boundingbox.setText(QCoreApplication.translate("MainWindow", u"Show Bounding Boxes", None))
        self.showCameraLandmarksChkBox.setText(QCoreApplication.translate("MainWindow", u"Show Body Landmarks", None))
        self.showCameraBoundingBoxChkBox.setText(QCoreApplication.translate("MainWindow", u"Show Bounding Box", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Camera Feed", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Key Points Visualization", None))
        self.show_skeleton_camera.setText(QCoreApplication.translate("MainWindow", u"Show in Skeleton", None))
        self.show_skeleton_white_frame.setText(QCoreApplication.translate("MainWindow", u"Show in Skeleton", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"ACTION:", None))
        self.add_action_button.setText(QCoreApplication.translate("MainWindow", u"Add Action", None))
        self.recording_button.setText(QCoreApplication.translate("MainWindow", u"START\n"
"RECORDING", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Interval", None))
        self.refresh_button.setText(QCoreApplication.translate("MainWindow", u"Refresh", None))
        self.delete_action_button.setText(QCoreApplication.translate("MainWindow", u"Delete", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"# of Sequences", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Status:", None))
        self.status_label.setText(QCoreApplication.translate("MainWindow", u"NOT RECORDING", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Dataset Details", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Folder Location", None))
        self.browseButton.setText(QCoreApplication.translate("MainWindow", u"Browse", None))
        self.refresh_action_list.setText(QCoreApplication.translate("MainWindow", u"Refresh", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"CPU Usage", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"RAM Usage", None))
        self.cpu_label.setText(QCoreApplication.translate("MainWindow", u"--", None))
        self.ram_label.setText(QCoreApplication.translate("MainWindow", u"--", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"TIME:", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"GPU Usage", None))
        self.gpu_label.setText(QCoreApplication.translate("MainWindow", u"--", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"FPS:", None))
        self.fps_label.setText(QCoreApplication.translate("MainWindow", u"--", None))
        self.MainTab.setTabText(self.MainTab.indexOf(self.createDatasetTab), QCoreApplication.translate("MainWindow", u"Create Dataset", None))
        self.menuARMIS.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuView.setTitle(QCoreApplication.translate("MainWindow", u"View", None))
    # retranslateUi

